using System.Diagnostics;
using System.IO.Compression;
using System.Xml.Linq;

namespace Reservoir.Tests;

public class SourcePackageTests
{
    [Test]
    public async Task PackageCompilesIntoConsumersWithoutRuntimeDependency()
    {
        string repositoryRoot = FindRepositoryRoot();
        string testRoot = Path.Combine(
            Path.GetTempPath(),
            "Reservoir.Packaging.Tests",
            Guid.NewGuid().ToString("N"));
        string packageDirectory = Path.Combine(testRoot, "packages");

        Directory.CreateDirectory(packageDirectory);

        try
        {
            await RunDotNet(
                repositoryRoot,
                "pack",
                Path.Combine(repositoryRoot, "src", "Reservoir", "Reservoir.csproj"),
                "--no-restore",
                "--configuration",
                "Release",
                "--output",
                packageDirectory,
                "/p:PackageVersion=0.0.0-integration");

            string packagePath = Directory.GetFiles(packageDirectory, "Reservoir.*.nupkg").Single();
            VerifyPackageContents(repositoryRoot, packagePath);

            await VerifyStandaloneConsumer(testRoot, packageDirectory);
            await VerifyIncompatibleConsumer(testRoot, packageDirectory);
            await VerifyIncompatibleLanguageVersion(testRoot, packageDirectory);
            await VerifyTwoProjectConsumer(testRoot, packageDirectory);
            await VerifyPublicOptIn(testRoot, packageDirectory);
            await VerifyForcedDiagnostics(testRoot, packageDirectory);
        }
        finally
        {
            Directory.Delete(testRoot, recursive: true);
        }
    }

    private static void VerifyPackageContents(string repositoryRoot, string packagePath)
    {
        using ZipArchive package = ZipFile.OpenRead(packagePath);
        ZipArchiveEntry[] sourceEntries = package.Entries
            .Where(entry => entry.FullName.StartsWith(
                "contentFiles/cs/net10.0/Reservoir/",
                StringComparison.Ordinal))
            .ToArray();
        int expectedSourceCount = Directory.GetFiles(
            Path.Combine(repositoryRoot, "src", "Reservoir"),
            "*.cs").Length;

        if (sourceEntries.Length != expectedSourceCount)
        {
            throw new InvalidOperationException(
                $"Package contained {sourceEntries.Length} sources; expected {expectedSourceCount}.");
        }

        if (package.Entries.Any(entry =>
                entry.FullName.StartsWith("lib/", StringComparison.OrdinalIgnoreCase)
                || entry.FullName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)))
        {
            throw new InvalidOperationException("Source package contained a library or assembly.");
        }

        if (!package.Entries.Any(entry => string.Equals(
                entry.FullName,
                "buildTransitive/Reservoir.targets",
                StringComparison.Ordinal)))
        {
            throw new InvalidOperationException(
                "Source package lacks its target-framework validation target.");
        }

        foreach (ZipArchiveEntry sourceEntry in sourceEntries)
        {
            using var reader = new StreamReader(sourceEntry.Open());
            string source = reader.ReadToEnd();
            if (!source.StartsWith("// <auto-generated/>", StringComparison.Ordinal)
                || !source.Contains("#nullable enable", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Packaged source '{sourceEntry.FullName}' lacks source-hygiene directives.");
            }
        }

        ZipArchiveEntry nuspecEntry = package.Entries.Single(entry =>
            entry.FullName.EndsWith(".nuspec", StringComparison.OrdinalIgnoreCase));
        using Stream nuspecStream = nuspecEntry.Open();
        XDocument nuspec = XDocument.Load(nuspecStream);
        XNamespace ns = nuspec.Root?.Name.Namespace
            ?? throw new InvalidOperationException("Package manifest has no root element.");
        XElement metadata = nuspec.Root.Element(ns + "metadata")
            ?? throw new InvalidOperationException("Package manifest has no metadata element.");

        (string Name, string Value)[] expectedMetadata =
        [
            ("title", "Reservoir"),
            ("authors", "Tom Longhurst"),
            ("developmentDependency", "true"),
            ("readme", "README.md"),
            ("projectUrl", "https://github.com/thomhurst/Reservoir"),
            ("description", "High-performance, allocation-conscious object pools distributed as source."),
            ("copyright", "Copyright © Tom Longhurst"),
            ("tags", "object-pool object-pooling pooling performance allocation-free source-only dotnet"),
        ];

        foreach ((string name, string expectedValue) in expectedMetadata)
        {
            string? actualValue = metadata.Element(ns + name)?.Value;
            if (!string.Equals(actualValue, expectedValue, StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Package metadata '{name}' was '{actualValue}', expected '{expectedValue}'.");
            }
        }

        XElement license = metadata.Element(ns + "license")
            ?? throw new InvalidOperationException("Package manifest has no license metadata.");
        if (!string.Equals(license.Attribute("type")?.Value, "expression", StringComparison.Ordinal)
            || !string.Equals(license.Value, "MIT", StringComparison.Ordinal))
        {
            throw new InvalidOperationException("Package license metadata is not SPDX MIT.");
        }

        XElement repository = metadata.Element(ns + "repository")
            ?? throw new InvalidOperationException("Package manifest has no repository metadata.");
        if (!string.Equals(repository.Attribute("type")?.Value, "git", StringComparison.Ordinal)
            || !string.Equals(
                repository.Attribute("url")?.Value,
                "https://github.com/thomhurst/Reservoir.git",
                StringComparison.Ordinal)
            || string.IsNullOrWhiteSpace(repository.Attribute("commit")?.Value))
        {
            throw new InvalidOperationException("Package repository metadata is incomplete.");
        }

        if (!metadata.Descendants(ns + "files").All(element =>
                string.Equals(element.Attribute("buildAction")?.Value, "Compile", StringComparison.Ordinal)))
        {
            throw new InvalidOperationException(
                "Package contentFiles metadata contains a non-Compile build action.");
        }
    }

    private static async Task VerifyIncompatibleConsumer(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "IncompatibleConsumer");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "IncompatibleConsumer.csproj"),
            ProjectFile(targetFramework: "net9.0"));

        await Restore(projectDirectory, "IncompatibleConsumer.csproj", packageDirectory);
        string output = await RunDotNetExpectingFailure(
            projectDirectory,
            "build",
            "IncompatibleConsumer.csproj",
            "--no-restore");
        if (!output.Contains("RESERVOIR001", StringComparison.Ordinal)
            || !output.Contains("Reservoir requires .NET 10.0 or later", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"Incompatible consumer lacked the expected framework error:{Environment.NewLine}{output}");
        }
    }

    private static async Task VerifyStandaloneConsumer(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "Consumer");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "Consumer.csproj"),
            ProjectFile(outputType: "Exe"));
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "Program.cs"),
            """
            using System;
            using Reservoir;

            ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
            System.Collections.Generic.List<int> list = pool.Rent();
            list.Add(42);
            pool.Return(list);
            Console.WriteLine(pool.Rent().Count);
            """);

        await Restore(projectDirectory, "Consumer.csproj", packageDirectory);
        string output = await RunDotNet(projectDirectory, "run", "--no-restore");
        if (!string.Equals(output.Trim(), "0", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Unexpected consumer output:{Environment.NewLine}{output}");
        }

        string publishDirectory = Path.Combine(testRoot, "publish");
        await RunDotNet(
            projectDirectory,
            "publish",
            "--no-restore",
            "--configuration",
            "Release",
            "--output",
            publishDirectory);

        if (Directory.GetFiles(publishDirectory, "Reservoir.dll").Length != 0)
        {
            throw new InvalidOperationException("Publish output contained Reservoir.dll.");
        }

        string depsJson = await File.ReadAllTextAsync(
            Directory.GetFiles(publishDirectory, "*.deps.json").Single());
        if (depsJson.Contains("Reservoir", StringComparison.Ordinal))
        {
            throw new InvalidOperationException("deps.json contained a Reservoir runtime dependency.");
        }
    }

    private static async Task VerifyIncompatibleLanguageVersion(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "IncompatibleLanguageVersion");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "IncompatibleLanguageVersion.csproj"),
            ProjectFile(languageVersion: "11"));

        await Restore(projectDirectory, "IncompatibleLanguageVersion.csproj", packageDirectory);
        string output = await RunDotNetExpectingFailure(
            projectDirectory,
            "build",
            "IncompatibleLanguageVersion.csproj",
            "--no-restore");
        if (!output.Contains("RESERVOIR002", StringComparison.Ordinal)
            || !output.Contains("Reservoir requires C# 12.0 or later", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"Incompatible language version lacked the expected error:{Environment.NewLine}{output}");
        }
    }

    private static async Task VerifyTwoProjectConsumer(
        string testRoot,
        string packageDirectory)
    {
        string libraryDirectory = Path.Combine(testRoot, "Library");
        string appDirectory = Path.Combine(testRoot, "DualApp");
        Directory.CreateDirectory(libraryDirectory);
        Directory.CreateDirectory(appDirectory);

        await File.WriteAllTextAsync(
            Path.Combine(libraryDirectory, "Library.csproj"),
            ProjectFile());
        await File.WriteAllTextAsync(
            Path.Combine(libraryDirectory, "PoolUser.cs"),
            """
            using Reservoir;

            namespace Library;

            public static class PoolUser
            {
                public static int RentCount()
                {
                    ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
                    return pool.Rent().Count;
                }
            }
            """);
        await File.WriteAllTextAsync(
            Path.Combine(appDirectory, "DualApp.csproj"),
            ProjectFile(
                outputType: "Exe",
                additionalItems:
                    "<ProjectReference Include=\"..\\Library\\Library.csproj\" />"));
        await File.WriteAllTextAsync(
            Path.Combine(appDirectory, "Program.cs"),
            """
            using System;
            using Library;
            using Reservoir;

            ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
            Console.WriteLine(pool.Rent().Count + PoolUser.RentCount());
            """);

        await Restore(appDirectory, "DualApp.csproj", packageDirectory);
        string output = await RunDotNet(appDirectory, "run", "--no-restore");
        if (!string.Equals(output.Trim(), "0", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Unexpected dual-project output:{Environment.NewLine}{output}");
        }
    }

    private static async Task VerifyPublicOptIn(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "PublicApi");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "PublicApi.csproj"),
            ProjectFile(defineConstants: "RESERVOIR_PUBLIC"));
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "PublicPool.cs"),
            """
            using Reservoir;

            public static class PublicPool
            {
                public static ObjectPool<object> Create() => new(() => new object());
            }
            """);

        await Restore(projectDirectory, "PublicApi.csproj", packageDirectory);
        await RunDotNet(projectDirectory, "build", "--no-restore");
    }

    private static async Task VerifyForcedDiagnostics(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "ForcedDiagnostics");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "ForcedDiagnostics.csproj"),
            ProjectFile(
                outputType: "Exe",
                defineConstants: "RESERVOIR_DIAGNOSTICS"));
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "Program.cs"),
            """
            using System;
            using Reservoir;

            ObjectPool<object> pool = new(() => new object(), maxCapacity: 1);
            object value = pool.Rent();
            pool.Return(value);

            try
            {
                pool.Return(value);
            }
            catch (InvalidOperationException)
            {
                Console.WriteLine("detected");
            }
            """);

        await Restore(projectDirectory, "ForcedDiagnostics.csproj", packageDirectory);
        string output = await RunDotNet(
            projectDirectory,
            "run",
            "--no-restore",
            "--configuration",
            "Release");

        if (!string.Equals(output.Trim(), "detected", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                $"Forced diagnostics did not detect a double return:{Environment.NewLine}{output}");
        }
    }

    private static string ProjectFile(
        string targetFramework = "net10.0",
        string? languageVersion = null,
        string? outputType = null,
        string? defineConstants = null,
        string? additionalItems = null)
        => $$"""
           <Project Sdk="Microsoft.NET.Sdk">
             <PropertyGroup>
               <TargetFramework>{{targetFramework}}</TargetFramework>
               <ImplicitUsings>disable</ImplicitUsings>
               <Nullable>enable</Nullable>
               {{(languageVersion is null ? string.Empty : $"<LangVersion>{languageVersion}</LangVersion>")}}
               {{(outputType is null ? string.Empty : $"<OutputType>{outputType}</OutputType>")}}
               {{(defineConstants is null ? string.Empty : $"<DefineConstants>{defineConstants}</DefineConstants>")}}
             </PropertyGroup>
             <ItemGroup>
               <PackageReference Include="Reservoir" Version="0.0.0-integration" />
               {{additionalItems}}
             </ItemGroup>
           </Project>
           """;

    private static Task<string> Restore(
        string workingDirectory,
        string projectFile,
        string packageDirectory)
        => RunDotNet(
            workingDirectory,
            "restore",
            projectFile,
            "--source",
            packageDirectory,
            "--packages",
            Path.Combine(Path.GetDirectoryName(packageDirectory)!, "global-packages"));

    private static async Task<string> RunDotNet(
        string workingDirectory,
        params string[] arguments)
    {
        (int exitCode, string output) = await ExecuteDotNet(workingDirectory, arguments);
        if (exitCode != 0)
        {
            throw new InvalidOperationException(
                $"dotnet {string.Join(' ', arguments)} failed with exit code {exitCode}."
                + Environment.NewLine
                + output);
        }

        return output;
    }

    private static async Task<string> RunDotNetExpectingFailure(
        string workingDirectory,
        params string[] arguments)
    {
        (int exitCode, string output) = await ExecuteDotNet(workingDirectory, arguments);
        if (exitCode == 0)
        {
            throw new InvalidOperationException(
                $"dotnet {string.Join(' ', arguments)} unexpectedly succeeded."
                + Environment.NewLine
                + output);
        }

        return output;
    }

    private static async Task<(int ExitCode, string Output)> ExecuteDotNet(
        string workingDirectory,
        params string[] arguments)
    {
        var startInfo = new ProcessStartInfo("dotnet")
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };

        foreach (string argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using Process process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Failed to start dotnet.");
        Task<string> standardOutput = process.StandardOutput.ReadToEndAsync();
        Task<string> standardError = process.StandardError.ReadToEndAsync();
        using var timeout = new CancellationTokenSource(TimeSpan.FromMinutes(2));

        try
        {
            await process.WaitForExitAsync(timeout.Token);
        }
        catch (OperationCanceledException)
        {
            process.Kill(entireProcessTree: true);
            throw new TimeoutException(
                $"dotnet {string.Join(' ', arguments)} exceeded two minutes.");
        }

        string output = await standardOutput;
        string error = await standardError;
        return (process.ExitCode, output + error);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Reservoir.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate Reservoir repository root.");
    }
}
