using System.Diagnostics;
using System.IO.Compression;

namespace Reservoir.Tests;

public class SourcePackageTests
{
    [Test]
    public async Task PackageCompilesIntoConsumersWithoutRuntimeDependency()
    {
        string repositoryRoot = FindRepositoryRoot();
        string testRoot = Path.Combine(
            Path.GetTempPath(),
            "Reservoir.Packaging.Tests",
            Guid.NewGuid().ToString("N"));
        string packageDirectory = Path.Combine(testRoot, "packages");

        Directory.CreateDirectory(packageDirectory);

        try
        {
            await RunDotNet(
                repositoryRoot,
                "pack",
                Path.Combine(repositoryRoot, "src", "Reservoir", "Reservoir.csproj"),
                "--no-restore",
                "--configuration",
                "Release",
                "--output",
                packageDirectory,
                "/p:PackageVersion=0.0.0-integration");

            string packagePath = Directory.GetFiles(packageDirectory, "Reservoir.*.nupkg").Single();
            VerifyPackageContents(repositoryRoot, packagePath);

            await VerifyStandaloneConsumer(testRoot, packageDirectory);
            await VerifyTwoProjectConsumer(testRoot, packageDirectory);
            await VerifyPublicOptIn(testRoot, packageDirectory);
        }
        finally
        {
            Directory.Delete(testRoot, recursive: true);
        }
    }

    private static void VerifyPackageContents(string repositoryRoot, string packagePath)
    {
        using ZipArchive package = ZipFile.OpenRead(packagePath);
        ZipArchiveEntry[] sourceEntries = package.Entries
            .Where(entry => entry.FullName.StartsWith(
                "contentFiles/cs/any/Reservoir/",
                StringComparison.Ordinal))
            .ToArray();
        int expectedSourceCount = Directory.GetFiles(
            Path.Combine(repositoryRoot, "src", "Reservoir"),
            "*.cs").Length;

        if (sourceEntries.Length != expectedSourceCount)
        {
            throw new InvalidOperationException(
                $"Package contained {sourceEntries.Length} sources; expected {expectedSourceCount}.");
        }

        if (package.Entries.Any(entry =>
                entry.FullName.StartsWith("lib/", StringComparison.OrdinalIgnoreCase)
                || entry.FullName.EndsWith(".dll", StringComparison.OrdinalIgnoreCase)))
        {
            throw new InvalidOperationException("Source package contained a library or assembly.");
        }

        foreach (ZipArchiveEntry sourceEntry in sourceEntries)
        {
            using var reader = new StreamReader(sourceEntry.Open());
            string source = reader.ReadToEnd();
            if (!source.StartsWith("// <auto-generated/>", StringComparison.Ordinal)
                || !source.Contains("#nullable enable", StringComparison.Ordinal))
            {
                throw new InvalidOperationException(
                    $"Packaged source '{sourceEntry.FullName}' lacks source-hygiene directives.");
            }
        }

        ZipArchiveEntry nuspecEntry = package.Entries.Single(entry =>
            entry.FullName.EndsWith(".nuspec", StringComparison.OrdinalIgnoreCase));
        using var nuspecReader = new StreamReader(nuspecEntry.Open());
        string nuspec = nuspecReader.ReadToEnd();
        if (!nuspec.Contains("<developmentDependency>true</developmentDependency>", StringComparison.Ordinal)
            || !nuspec.Contains("buildAction=\"Compile\"", StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "Package metadata lacks developmentDependency or Compile contentFiles metadata.");
        }
    }

    private static async Task VerifyStandaloneConsumer(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "Consumer");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "Consumer.csproj"),
            ProjectFile(outputType: "Exe"));
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "Program.cs"),
            """
            using System;
            using Reservoir;

            ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
            System.Collections.Generic.List<int> list = pool.Rent();
            list.Add(42);
            pool.Return(list);
            Console.WriteLine(pool.Rent().Count);
            """);

        await Restore(projectDirectory, "Consumer.csproj", packageDirectory);
        string output = await RunDotNet(projectDirectory, "run", "--no-restore");
        if (!string.Equals(output.Trim(), "0", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Unexpected consumer output:{Environment.NewLine}{output}");
        }

        string publishDirectory = Path.Combine(testRoot, "publish");
        await RunDotNet(
            projectDirectory,
            "publish",
            "--no-restore",
            "--configuration",
            "Release",
            "--output",
            publishDirectory);

        if (Directory.GetFiles(publishDirectory, "Reservoir.dll").Length != 0)
        {
            throw new InvalidOperationException("Publish output contained Reservoir.dll.");
        }

        string depsJson = await File.ReadAllTextAsync(
            Directory.GetFiles(publishDirectory, "*.deps.json").Single());
        if (depsJson.Contains("Reservoir", StringComparison.Ordinal))
        {
            throw new InvalidOperationException("deps.json contained a Reservoir runtime dependency.");
        }
    }

    private static async Task VerifyTwoProjectConsumer(
        string testRoot,
        string packageDirectory)
    {
        string libraryDirectory = Path.Combine(testRoot, "Library");
        string appDirectory = Path.Combine(testRoot, "DualApp");
        Directory.CreateDirectory(libraryDirectory);
        Directory.CreateDirectory(appDirectory);

        await File.WriteAllTextAsync(
            Path.Combine(libraryDirectory, "Library.csproj"),
            ProjectFile());
        await File.WriteAllTextAsync(
            Path.Combine(libraryDirectory, "PoolUser.cs"),
            """
            using Reservoir;

            namespace Library;

            public static class PoolUser
            {
                public static int RentCount()
                {
                    ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
                    return pool.Rent().Count;
                }
            }
            """);
        await File.WriteAllTextAsync(
            Path.Combine(appDirectory, "DualApp.csproj"),
            ProjectFile(
                outputType: "Exe",
                additionalItems:
                    "<ProjectReference Include=\"..\\Library\\Library.csproj\" />"));
        await File.WriteAllTextAsync(
            Path.Combine(appDirectory, "Program.cs"),
            """
            using System;
            using Library;
            using Reservoir;

            ListPool<int> pool = new(maxRetainedCapacity: 16, maxCapacity: 1);
            Console.WriteLine(pool.Rent().Count + PoolUser.RentCount());
            """);

        await Restore(appDirectory, "DualApp.csproj", packageDirectory);
        string output = await RunDotNet(appDirectory, "run", "--no-restore");
        if (!string.Equals(output.Trim(), "0", StringComparison.Ordinal))
        {
            throw new InvalidOperationException($"Unexpected dual-project output:{Environment.NewLine}{output}");
        }
    }

    private static async Task VerifyPublicOptIn(
        string testRoot,
        string packageDirectory)
    {
        string projectDirectory = Path.Combine(testRoot, "PublicApi");
        Directory.CreateDirectory(projectDirectory);
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "PublicApi.csproj"),
            ProjectFile(defineConstants: "RESERVOIR_PUBLIC"));
        await File.WriteAllTextAsync(
            Path.Combine(projectDirectory, "PublicPool.cs"),
            """
            using Reservoir;

            public static class PublicPool
            {
                public static ObjectPool<object> Create() => new(() => new object());
            }
            """);

        await Restore(projectDirectory, "PublicApi.csproj", packageDirectory);
        await RunDotNet(projectDirectory, "build", "--no-restore");
    }

    private static string ProjectFile(
        string? outputType = null,
        string? defineConstants = null,
        string? additionalItems = null)
        => $$"""
           <Project Sdk="Microsoft.NET.Sdk">
             <PropertyGroup>
               <TargetFramework>net10.0</TargetFramework>
               <ImplicitUsings>disable</ImplicitUsings>
               <Nullable>enable</Nullable>
               {{(outputType is null ? string.Empty : $"<OutputType>{outputType}</OutputType>")}}
               {{(defineConstants is null ? string.Empty : $"<DefineConstants>{defineConstants}</DefineConstants>")}}
             </PropertyGroup>
             <ItemGroup>
               <PackageReference Include="Reservoir" Version="0.0.0-integration" />
               {{additionalItems}}
             </ItemGroup>
           </Project>
           """;

    private static Task<string> Restore(
        string workingDirectory,
        string projectFile,
        string packageDirectory)
        => RunDotNet(
            workingDirectory,
            "restore",
            projectFile,
            "--source",
            packageDirectory);

    private static async Task<string> RunDotNet(
        string workingDirectory,
        params string[] arguments)
    {
        var startInfo = new ProcessStartInfo("dotnet")
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };

        foreach (string argument in arguments)
        {
            startInfo.ArgumentList.Add(argument);
        }

        using Process process = Process.Start(startInfo)
            ?? throw new InvalidOperationException("Failed to start dotnet.");
        Task<string> standardOutput = process.StandardOutput.ReadToEndAsync();
        Task<string> standardError = process.StandardError.ReadToEndAsync();
        using var timeout = new CancellationTokenSource(TimeSpan.FromMinutes(2));

        try
        {
            await process.WaitForExitAsync(timeout.Token);
        }
        catch (OperationCanceledException)
        {
            process.Kill(entireProcessTree: true);
            throw new TimeoutException(
                $"dotnet {string.Join(' ', arguments)} exceeded two minutes.");
        }

        string output = await standardOutput;
        string error = await standardError;
        if (process.ExitCode != 0)
        {
            throw new InvalidOperationException(
                $"dotnet {string.Join(' ', arguments)} failed with exit code {process.ExitCode}."
                + Environment.NewLine
                + output
                + error);
        }

        return output + error;
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null)
        {
            if (File.Exists(Path.Combine(directory.FullName, "Reservoir.slnx")))
            {
                return directory.FullName;
            }

            directory = directory.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate Reservoir repository root.");
    }
}
