<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Reservoir\Reservoir.csproj" />
  </ItemGroup>

  <Target Name="ValidateDocumentationSnippets" BeforeTargets="CoreCompile">
    <Exec
      Command="pwsh -NoProfile -File &quot;$(MSBuildThisFileDirectory)..\..\build\Test-DocumentationSnippets.ps1&quot; -RepositoryPath &quot;$(MSBuildThisFileDirectory)..\..&quot;" />
  </Target>
</Project>
