// <auto-generated/>
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.InteropServices;

namespace Reservoir;

/// <summary>
/// Base class that pushes a derived class's fields one cache line past the object header.
/// </summary>
/// <remarks>
/// The runtime ignores <see cref="StructLayoutAttribute.Size"/> on classes that hold references
/// and rejects explicit layout on generic types, so mutable per-thread and per-stripe state pads
/// itself by deriving from this class and having its most derived class declare a trailing
/// <see cref="CacheLinePad"/> field, which the runtime places after every base-class field. With
/// both pads in place, neighbouring objects never share a cache line with the hot fields, which
/// matters once the GC compacts objects allocated by different threads next to each other.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
[StructLayout(LayoutKind.Explicit)]
internal abstract class CacheLinePadded
{
    internal const int CacheLineSize = 64;

#pragma warning disable CS0169 // The field is only there to occupy space.
    [FieldOffset(CacheLineSize - sizeof(long))]
    private readonly long _leadingPad;
#pragma warning restore CS0169
}

/// <summary>Occupies one cache line as the trailing field of a padded class.</summary>
[StructLayout(LayoutKind.Sequential, Size = CacheLinePadded.CacheLineSize)]
internal readonly struct CacheLinePad
{
}
