// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;

namespace Reservoir;

/// <summary>
/// Provides pools of reusable <see cref="CancellationTokenSource"/> instances.
/// </summary>
/// <remarks>
/// A renter must dispose each rental exactly once as the source's sole owner. No token readers or
/// cancellation operations may remain in flight because <c>CancellationTokenSource.TryReset()</c>
/// is not thread-safe with concurrent use. Linked sources are not supported and should be disposed.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class CancellationTokenSourcePool : IDisposable
{
    private readonly ObjectPool<PooledCancellationTokenSource, Policy> _pool;

    /// <summary>Gets the shared pool.</summary>
    public static CancellationTokenSourcePool Shared { get; } = new();

    /// <summary>Initializes a pool with the default capacity.</summary>
    public CancellationTokenSourcePool()
        : this(ObjectPool<PooledCancellationTokenSource, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom capacity.</summary>
    public CancellationTokenSourcePool(int maxCapacity)
    {
        _pool = new ObjectPool<PooledCancellationTokenSource, Policy>(
            new Policy(this),
            maxCapacity);
    }

    /// <summary>Gets the maximum number of sources retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Rents a source that returns to this pool when disposed.</summary>
    public CancellationTokenSource Rent() => _pool.Rent();

    /// <summary>Rents a source owned by a stack-only lease that returns it on disposal.</summary>
    public Lease RentScoped()
        => new(_pool.RentScoped());

    /// <summary>
    /// Rents a source owned by a stack-only lease and also exposes the source directly.
    /// </summary>
    public Lease RentScoped(out CancellationTokenSource source)
    {
        PooledLease<PooledCancellationTokenSource, Policy> lease = _pool.RentScoped(
            out PooledCancellationTokenSource pooledSource);
        source = pooledSource;
        return new Lease(lease);
    }

    /// <summary>
    /// Disposes all retained sources while leaving the pool usable.
    /// </summary>
    public void Clear() => _pool.Clear();

    /// <summary>
    /// Disposes all retained sources and permanently closes the pool.
    /// </summary>
    /// <remarks>Disposing <see cref="Shared"/> clears it without closing it.</remarks>
    public void Dispose()
    {
        if (ReferenceEquals(this, Shared))
        {
            _pool.Clear();
            return;
        }

        _pool.Dispose();
    }

    private void Return(PooledCancellationTokenSource source) => _pool.Return(source);

    [DebuggerNonUserCode]
    internal sealed class PooledCancellationTokenSource : CancellationTokenSource
    {
        private readonly CancellationTokenSourcePool _owner;

        internal PooledCancellationTokenSource(CancellationTokenSourcePool owner)
        {
            _owner = owner;
        }

        internal void DisposePermanently() => base.Dispose(true);

        /// <inheritdoc />
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _owner.Return(this);
            }
        }
    }

    /// <summary>Owns a rented source and returns it on disposal.</summary>
    [DebuggerNonUserCode]
    public ref struct Lease
    {
        private PooledLease<PooledCancellationTokenSource, Policy> _lease;

        internal Lease(PooledLease<PooledCancellationTokenSource, Policy> lease)
        {
            _lease = lease;
        }

        /// <summary>Gets the rented source while this lease owns it.</summary>
        public readonly CancellationTokenSource Value
            => _lease.Value;

        /// <summary>Returns the source. Repeated calls and stale copies are ignored.</summary>
        public void Dispose() => _lease.Dispose();
    }

    internal readonly struct Policy : IPooledObjectPolicy<PooledCancellationTokenSource>
    {
        private readonly CancellationTokenSourcePool _owner;

        internal Policy(CancellationTokenSourcePool owner)
        {
            _owner = owner;
        }

        public PooledCancellationTokenSource Create() => new(_owner);

        public bool TryReset(PooledCancellationTokenSource source)
        {
#if NET6_0_OR_GREATER
            // TryReset disarms the runtime timer and rejects reuse once its callback was queued.
            // ObjectPool permanently disposes the source whenever this returns false.
            return source.TryReset();
#else
            return false;
#endif
        }

        public void Destroy(PooledCancellationTokenSource source) => source.DisposePermanently();
    }
}
