// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;

namespace Reservoir;

/// <summary>
/// Provides pools of reusable <see cref="CancellationTokenSource"/> instances.
/// </summary>
/// <remarks>
/// A renter must be the source's sole owner when returning it. No token readers or cancellation
/// operations may remain in flight because <c>CancellationTokenSource.TryReset()</c> is not
/// thread-safe with concurrent use. Linked sources are not supported and should be disposed.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class CancellationTokenSourcePool
{
    private readonly ObjectPool<CancellationTokenSource, Policy> _pool;

    /// <summary>Gets the shared pool.</summary>
    public static CancellationTokenSourcePool Shared { get; } = new();

    /// <summary>Initializes a pool with the default capacity.</summary>
    public CancellationTokenSourcePool()
        : this(ObjectPool<CancellationTokenSource, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom capacity.</summary>
    public CancellationTokenSourcePool(int maxCapacity)
    {
        _pool = new ObjectPool<CancellationTokenSource, Policy>(maxCapacity);
    }

    /// <summary>Gets the maximum number of sources retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Rents a source whose token has not been canceled.</summary>
    public CancellationTokenSource Rent() => _pool.Rent();

    /// <summary>Rents a source owned by a stack-only lease that returns it on disposal.</summary>
    public Lease RentScoped() => new(_pool.RentScoped());

    /// <summary>
    /// Rents a source owned by a stack-only lease and also exposes the source directly.
    /// </summary>
    public Lease RentScoped(out CancellationTokenSource source)
        => new(_pool.RentScoped(out source));

    /// <summary>
    /// Returns a solely owned source. Canceled sources are disposed instead of retained.
    /// </summary>
    public void Return(CancellationTokenSource source) => _pool.Return(source);

    /// <summary>Owns a rented source and returns it on disposal.</summary>
    [ExcludeFromCodeCoverage]
    [DebuggerNonUserCode]
    public ref struct Lease
    {
        private PooledLease<CancellationTokenSource, Policy> _lease;

        internal Lease(PooledLease<CancellationTokenSource, Policy> lease)
        {
            _lease = lease;
        }

        /// <summary>Gets the rented source while this lease owns it.</summary>
        public readonly CancellationTokenSource Value => _lease.Value;

        /// <summary>Returns the source. Repeated calls on this lease are ignored.</summary>
        public void Dispose() => _lease.Dispose();
    }

    internal readonly struct Policy : IPooledObjectPolicy<CancellationTokenSource>
    {
        public CancellationTokenSource Create() => new();

        public bool TryReset(CancellationTokenSource source)
        {
#if NET6_0_OR_GREATER
            return source.TryReset();
#else
            return false;
#endif
        }
    }
}
