// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Provides pools of reusable <see cref="Dictionary{TKey,TValue}"/> instances.</summary>
/// <typeparam name="TKey">The key type.</typeparam>
/// <typeparam name="TValue">The value type.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class DictionaryPool<TKey, TValue>
    where TKey : notnull
{
    private readonly ObjectPool<Dictionary<TKey, TValue>, Policy> _pool;
    private InstanceThreadLocalFrontTier<Dictionary<TKey, TValue>> _scopedTier;

    /// <summary>Gets the default largest dictionary capacity retained by a pool.</summary>
    public const int DefaultMaximumRetainedCapacity = 1024;

    /// <summary>Gets the shared pool using the default key comparer.</summary>
    public static DictionaryPool<TKey, TValue> Shared { get; } = new();

    /// <summary>
    /// Gets an opt-in default-comparer pool that retains one dictionary per participating
    /// thread before using <see cref="Shared"/> as a bounded fallback.
    /// </summary>
    public static ThreadLocalPool ThreadLocalShared { get; } = new();

    /// <summary>Initializes a pool with default limits and key comparer.</summary>
    public DictionaryPool()
        : this(null)
    {
    }

    /// <summary>Initializes a pool with default limits and a custom key comparer.</summary>
    public DictionaryPool(IEqualityComparer<TKey>? comparer)
        : this(
            comparer,
            DefaultMaximumRetainedCapacity,
            ObjectPool<Dictionary<TKey, TValue>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom dictionary capacity limit.</summary>
    public DictionaryPool(int maxRetainedCapacity)
        : this(null, maxRetainedCapacity)
    {
    }

    /// <summary>Initializes a pool with a custom key comparer and dictionary capacity limit.</summary>
    public DictionaryPool(IEqualityComparer<TKey>? comparer, int maxRetainedCapacity)
        : this(
            comparer,
            maxRetainedCapacity,
            ObjectPool<Dictionary<TKey, TValue>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with custom limits and the default key comparer.</summary>
    public DictionaryPool(int maxRetainedCapacity, int maxCapacity)
        : this(null, maxRetainedCapacity, maxCapacity)
    {
    }

    /// <summary>Initializes a pool with a custom comparer and custom limits.</summary>
    public DictionaryPool(
        IEqualityComparer<TKey>? comparer,
        int maxRetainedCapacity,
        int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegative(maxRetainedCapacity);
#else
        if (maxRetainedCapacity < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(maxRetainedCapacity),
                maxRetainedCapacity,
                null);
        }
#endif
        Comparer = comparer ?? EqualityComparer<TKey>.Default;
        MaximumRetainedCapacity = maxRetainedCapacity;
        _pool = new ObjectPool<Dictionary<TKey, TValue>, Policy>(
            new Policy(Comparer, maxRetainedCapacity),
            maxCapacity);
    }

    /// <summary>Gets the comparer used by dictionaries from this pool.</summary>
    public IEqualityComparer<TKey> Comparer { get; }

    /// <summary>Gets the maximum number of dictionaries retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets the largest dictionary capacity retained by this pool.</summary>
    public int MaximumRetainedCapacity { get; }

    /// <summary>Rents an empty dictionary.</summary>
    public Dictionary<TKey, TValue> Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Rents an empty dictionary owned by a stack-only thread-local lease.</summary>
    public Lease RentScoped()
        => new(this, _scopedTier.Rent(_pool));

    /// <summary>
    /// Rents an empty dictionary owned by a stack-only thread-local lease and exposes it directly.
    /// </summary>
    public Lease RentScoped(out Dictionary<TKey, TValue> dictionary)
    {
        dictionary = _scopedTier.Rent(_pool);
        return new Lease(this, dictionary);
    }

    /// <summary>Returns a dictionary, clearing it when retained and discarding it when incompatible or too large.</summary>
    public void Return(Dictionary<TKey, TValue> dictionary)
    {
        ThrowIfNull(dictionary);

        if (!TryReset(dictionary))
        {
            return;
        }

        _pool.ReturnWithoutReset(dictionary);
    }

    private bool TryReset(Dictionary<TKey, TValue> dictionary)
    {
        if (Policy.Reset(dictionary, Comparer, MaximumRetainedCapacity))
        {
            return true;
        }

        _pool.Destroy(dictionary);
        return false;
    }

    private void ReturnScoped(Dictionary<TKey, TValue> dictionary)
    {
        if (!TryReset(dictionary))
        {
            return;
        }

        if (!_scopedTier.TryReturn(dictionary))
        {
            _pool.ReturnWithoutReset(dictionary);
        }
    }

    private static void ThrowIfNull(Dictionary<TKey, TValue>? dictionary)
    {
        if (dictionary is null)
        {
            throw new ArgumentNullException("obj");
        }
    }

    private readonly struct Policy(
        IEqualityComparer<TKey> comparer,
        int maxRetainedCapacity) : IPooledObjectPolicy<Dictionary<TKey, TValue>>
    {
        public Dictionary<TKey, TValue> Create() => new(comparer);

        internal static bool Reset(
            Dictionary<TKey, TValue> obj,
            IEqualityComparer<TKey> expectedComparer,
            int maximumRetainedCapacity)
        {
            if (!ReferenceEquals(obj.Comparer, expectedComparer))
            {
                return false;
            }

#if NETSTANDARD2_0
            // Without a readable capacity the retention bound cannot be enforced, so discard.
            if (!CollectionCapacity<Dictionary<TKey, TValue>>.IsAvailable
                || CollectionCapacity<Dictionary<TKey, TValue>>.Get(obj) > maximumRetainedCapacity)
            {
                return false;
            }
#else
            if (obj.EnsureCapacity(0) > maximumRetainedCapacity)
            {
                return false;
            }
#endif

            obj.Clear();
            return true;
        }

        public bool TryReset(Dictionary<TKey, TValue> obj)
            => Reset(obj, comparer, maxRetainedCapacity);

        // Mirrors the interface default method; the explicit implementation keeps the constrained
        // Destroy call devirtualized instead of boxing this struct on every discarded object.
        public void Destroy(Dictionary<TKey, TValue> obj)
        {
            if (obj is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }

    /// <summary>Owns a thread-local dictionary rental and returns it when disposed.</summary>
    public ref struct Lease
    {
        private readonly DictionaryPool<TKey, TValue>? _pool;
        private ScopedPoolLease<Dictionary<TKey, TValue>> _lease;

        internal Lease(
            DictionaryPool<TKey, TValue> pool,
            Dictionary<TKey, TValue> dictionary)
        {
            _pool = pool;
            _lease = new ScopedPoolLease<Dictionary<TKey, TValue>>(dictionary);
        }

        /// <summary>Gets the rented dictionary while this lease owns it.</summary>
        public readonly Dictionary<TKey, TValue> Value => _lease.Value;

        /// <summary>Returns the dictionary. Repeated calls and stale copies are ignored.</summary>
        public void Dispose()
        {
            if (_lease.TryRelease(out Dictionary<TKey, TValue> dictionary))
            {
                _pool!.ReturnScoped(dictionary);
            }
        }
    }

    /// <summary>Provides thread-local-first access to <see cref="Shared"/>.</summary>
    public sealed class ThreadLocalPool
    {
        internal ThreadLocalPool()
        {
        }

        /// <summary>Rents an empty dictionary from the current thread or shared fallback.</summary>
        public Dictionary<TKey, TValue> Rent()
            => ThreadLocalFrontTier<Dictionary<TKey, TValue>, Policy>.Rent(Shared._pool);

        /// <summary>Returns a dictionary to the current thread or shared fallback.</summary>
        public void Return(Dictionary<TKey, TValue> dictionary)
        {
            ThrowIfNull(dictionary);
            if (!Shared.TryReset(dictionary))
            {
                return;
            }

            if (!ThreadLocalFrontTier<Dictionary<TKey, TValue>, Policy>.TryReturn(dictionary))
            {
                Shared._pool.ReturnWithoutReset(dictionary);
            }
        }
    }
}
