// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Provides pools of reusable <see cref="HashSet{T}"/> instances.</summary>
/// <typeparam name="T">The element type.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class HashSetPool<T>
{
    private readonly ObjectPool<HashSet<T>, Policy> _pool;
    private InstanceThreadLocalFrontTier<HashSet<T>> _scopedTier;

    /// <summary>Gets the default largest hash-set capacity retained by a pool.</summary>
    public const int DefaultMaximumRetainedCapacity = 1024;

    /// <summary>Gets the shared pool using the default element comparer.</summary>
    public static HashSetPool<T> Shared { get; } = new();

    /// <summary>
    /// Gets an opt-in default-comparer pool that retains one set per participating thread
    /// before using <see cref="Shared"/> as a bounded fallback.
    /// </summary>
    public static ThreadLocalPool ThreadLocalShared { get; } = new();

    /// <summary>Initializes a pool with default limits and element comparer.</summary>
    public HashSetPool()
        : this(null)
    {
    }

    /// <summary>Initializes a pool with default limits and a custom element comparer.</summary>
    public HashSetPool(IEqualityComparer<T>? comparer)
        : this(
            comparer,
            DefaultMaximumRetainedCapacity,
            ObjectPool<HashSet<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom hash-set capacity limit.</summary>
    public HashSetPool(int maxRetainedCapacity)
        : this(null, maxRetainedCapacity)
    {
    }

    /// <summary>Initializes a pool with a custom element comparer and hash-set capacity limit.</summary>
    public HashSetPool(IEqualityComparer<T>? comparer, int maxRetainedCapacity)
        : this(
            comparer,
            maxRetainedCapacity,
            ObjectPool<HashSet<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with custom limits and the default element comparer.</summary>
    public HashSetPool(int maxRetainedCapacity, int maxCapacity)
        : this(null, maxRetainedCapacity, maxCapacity)
    {
    }

    /// <summary>Initializes a pool with a custom comparer and custom limits.</summary>
    public HashSetPool(
        IEqualityComparer<T>? comparer,
        int maxRetainedCapacity,
        int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegative(maxRetainedCapacity);
#else
        if (maxRetainedCapacity < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(maxRetainedCapacity),
                maxRetainedCapacity,
                null);
        }
#endif
        Comparer = comparer ?? EqualityComparer<T>.Default;
        MaximumRetainedCapacity = maxRetainedCapacity;
        _pool = new ObjectPool<HashSet<T>, Policy>(
            new Policy(Comparer, maxRetainedCapacity),
            maxCapacity);
    }

    /// <summary>Gets the comparer used by hash sets from this pool.</summary>
    public IEqualityComparer<T> Comparer { get; }

    /// <summary>Gets the maximum number of hash sets retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets the largest hash-set capacity retained by this pool.</summary>
    public int MaximumRetainedCapacity { get; }

    /// <summary>Rents an empty hash set.</summary>
    public HashSet<T> Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Rents an empty hash set owned by a stack-only thread-local lease.</summary>
    public Lease RentScoped()
        => new(this, _scopedTier.Rent(_pool));

    /// <summary>
    /// Rents an empty hash set owned by a stack-only thread-local lease and exposes it directly.
    /// </summary>
    public Lease RentScoped(out HashSet<T> set)
    {
        set = _scopedTier.Rent(_pool);
        return new Lease(this, set);
    }

    /// <summary>Returns a hash set, clearing it when retained and discarding it when incompatible or too large.</summary>
    public void Return(HashSet<T> set)
    {
        ThrowIfNull(set);

        if (!TryReset(set))
        {
            return;
        }

        _pool.ReturnWithoutReset(set);
    }

    private bool TryReset(HashSet<T> set)
    {
        if (Policy.Reset(set, Comparer, MaximumRetainedCapacity))
        {
            return true;
        }

        _pool.Destroy(set);
        return false;
    }

    private void ReturnScoped(HashSet<T> set)
    {
        if (!TryReset(set))
        {
            return;
        }

        if (!_scopedTier.TryReturn(set))
        {
            _pool.ReturnWithoutReset(set);
        }
    }

    private static void ThrowIfNull(HashSet<T>? set)
    {
        if (set is null)
        {
            throw new ArgumentNullException("obj");
        }
    }

    private readonly struct Policy(
        IEqualityComparer<T> comparer,
        int maxRetainedCapacity) : IPooledObjectPolicy<HashSet<T>>
    {
#if NETSTANDARD2_0
        private static readonly Func<HashSet<T>, int, int>? s_ensureCapacity
            = RuntimeCompatibility.CreateEnsureCapacity<HashSet<T>>();
#endif

        public HashSet<T> Create() => new(comparer);

        internal static bool Reset(
            HashSet<T> obj,
            IEqualityComparer<T> expectedComparer,
            int maximumRetainedCapacity)
        {
            if (!ReferenceEquals(obj.Comparer, expectedComparer))
            {
                return false;
            }

#if NETSTANDARD2_0
            if (s_ensureCapacity is null)
            {
                obj.Clear();
                obj.TrimExcess();
                return true;
            }

            if (s_ensureCapacity(obj, 0) > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
#else
            if (obj.EnsureCapacity(0) > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
#endif
        }

        public bool TryReset(HashSet<T> obj)
            => Reset(obj, comparer, maxRetainedCapacity);
    }

    /// <summary>Owns a thread-local hash-set rental and returns it when disposed.</summary>
    public ref struct Lease
    {
        private readonly HashSetPool<T>? _pool;
        private ScopedPoolLease<HashSet<T>> _lease;

        internal Lease(HashSetPool<T> pool, HashSet<T> set)
        {
            _pool = pool;
            _lease = new ScopedPoolLease<HashSet<T>>(set);
        }

        /// <summary>Gets the rented hash set while this lease owns it.</summary>
        public readonly HashSet<T> Value => _lease.Value;

        /// <summary>Returns the hash set. Repeated calls and stale copies are ignored.</summary>
        public void Dispose()
        {
            if (_lease.TryRelease(out HashSet<T> set))
            {
                _pool!.ReturnScoped(set);
            }
        }
    }

    /// <summary>Provides thread-local-first access to <see cref="Shared"/>.</summary>
    public sealed class ThreadLocalPool
    {
        internal ThreadLocalPool()
        {
        }

        /// <summary>Rents an empty set from the current thread or shared fallback.</summary>
        public HashSet<T> Rent()
            => ThreadLocalFrontTier<HashSet<T>, Policy>.Rent(Shared._pool);

        /// <summary>Returns a set to the current thread or shared fallback.</summary>
        public void Return(HashSet<T> set)
        {
            ThrowIfNull(set);
            if (!Shared.TryReset(set))
            {
                return;
            }

            if (!ThreadLocalFrontTier<HashSet<T>, Policy>.TryReturn(set))
            {
                Shared._pool.ReturnWithoutReset(set);
            }
        }
    }
}
