// <auto-generated/>
#nullable enable

namespace Reservoir;

/// <summary>
/// Marks a pooled-object policy whose <see cref="IPooledObjectPolicy{T}.TryReset"/> never throws,
/// letting pools skip the exception-handling wrapper around reset calls.
/// </summary>
/// <remarks>
/// The wrapper exists to destroy an object when its reset throws. Opting in removes that call
/// overhead from every return; in exchange, if a marked policy throws from
/// <see cref="IPooledObjectPolicy{T}.TryReset"/> anyway, the exception propagates without the
/// object being destroyed. Only apply this marker to policies whose reset provably cannot throw.
/// </remarks>
public
interface INonThrowingResetPolicy
{
}
