// <auto-generated/>
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Reservoir;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal struct InstanceThreadLocalFrontTier<T>
    where T : class
{
    private ThreadLocal<Slot>? _slots;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T Rent<TPolicy>(ObjectPool<T, TPolicy> fallback, out Slot slot)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        slot = GetSlot();
        T? item = slot.Item;
        if (item is null)
        {
            return fallback.RentWithoutLifecycle();
        }

        slot.Item = null;
        return item;
    }

    // Stack-only leases carry their renting thread's slot back, avoiding a second lookup.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool TryReturn(Slot slot, T item)
    {
        if (slot.Item is not null)
        {
            return false;
        }

        slot.Item = item;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private Slot GetSlot()
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        return (slots ?? InitializeSlots()).Value!;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private ThreadLocal<Slot> InitializeSlots()
    {
        var created = new ThreadLocal<Slot>(static () => new PaddedSlot());
        ThreadLocal<Slot>? existing = Interlocked.CompareExchange(ref _slots, created, null);
        if (existing is null)
        {
            return created;
        }

        created.Dispose();
        return existing;
    }

    // The slot also owns the primary lease version, avoiding a separate thread-static lookup.
    // Nested rentals use the existing state ring. The leading and trailing pads still isolate
    // each thread's writes; see CacheLinePadded.
    internal class Slot : ScopedPoolLeaseState
    {
        internal T? Item;
    }

    private sealed class PaddedSlot : Slot
    {
#pragma warning disable CS0169 // The field is only there to occupy space.
        private readonly CacheLinePad _trailingPad;
#pragma warning restore CS0169
    }
}
