// <auto-generated/>
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Reservoir;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal struct InstanceThreadLocalFrontTier<T>
    where T : class
{
    private ThreadLocal<Slot>? _slots;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T Rent<TPolicy>(ObjectPool<T, TPolicy> fallback)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        Slot slot = GetSlot();
        T? item = slot.Item;
        if (item is null)
        {
            return fallback.RentWithoutLifecycle();
        }

        slot.Item = null;
        return item;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryReturn(T item)
    {
        Slot slot = GetSlot();
        if (slot.Item is not null)
        {
            return false;
        }

        slot.Item = item;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private Slot GetSlot()
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        return (slots ?? InitializeSlots()).Value!;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private ThreadLocal<Slot> InitializeSlots()
    {
        var created = new ThreadLocal<Slot>(static () => new PaddedSlot());
        ThreadLocal<Slot>? existing = Interlocked.CompareExchange(ref _slots, created, null);
        if (existing is null)
        {
            return created;
        }

        created.Dispose();
        return existing;
    }

    // The base-class leading pad and the allocated subclass's trailing pad keep each thread's
    // slot on its own cache lines; see CacheLinePadded.
    private class Slot : CacheLinePadded
    {
        internal T? Item;
    }

    private sealed class PaddedSlot : Slot
    {
#pragma warning disable CS0169 // The field is only there to occupy space.
        private readonly CacheLinePad _trailingPad;
#pragma warning restore CS0169
    }
}
