// <auto-generated/>
#nullable enable

using System;

namespace Reservoir;

/// <summary>
/// Creates pooled objects, prepares returned objects for reuse, and destroys discarded objects.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
public
interface IPooledObjectPolicy<T>
    where T : class
{
    /// <summary>Creates an object when the pool is empty.</summary>
    T Create();

    /// <summary>
    /// Resets an object before it is retained. Returns <see langword="false"/> to discard it.
    /// </summary>
    bool TryReset(T obj);

    /// <summary>Destroys an object that cannot be retained by the pool.</summary>
    /// <remarks>
    /// The netstandard2.0 contract requires an implementation. Modern targets provide a default
    /// that disposes objects implementing <see cref="IDisposable"/>. Implement this method on a
    /// struct policy to preserve by-reference dispatch and avoid boxing on discarded objects.
    /// </remarks>
#if NETCOREAPP3_0_OR_GREATER
    void Destroy(T obj)
    {
        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
#else
    void Destroy(T obj);
#endif
}
