// <auto-generated/>
#nullable enable

namespace Reservoir;

/// <summary>
/// Creates pooled objects, prepares returned objects for reuse, and destroys discarded objects.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
interface IPooledObjectPolicy<T>
    where T : class
{
    /// <summary>Creates an object when the pool is empty.</summary>
    T Create();

    /// <summary>
    /// Resets an object before it is retained. Returns <see langword="false"/> to discard it.
    /// </summary>
    bool TryReset(T obj);
}
