// <auto-generated/>
#nullable enable

namespace Reservoir;

/// <summary>
/// Adds custom destruction to a pooled-object policy.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
public
interface IPooledObjectDestroyPolicy<T> : IPooledObjectPolicy<T>
    where T : class
{
#if !NETCOREAPP3_0_OR_GREATER
    /// <summary>Destroys an object that cannot be retained by the pool.</summary>
    void Destroy(T obj);
#endif
}
