// <auto-generated/>
#nullable enable

namespace Reservoir;

/// <summary>
/// Identifies a pooled-object policy with custom destruction.
/// </summary>
/// <remarks>
/// Destruction is declared by <see cref="IPooledObjectPolicy{T}"/> on every target framework.
/// This interface is a marker; explicit implementations must implement the base interface's
/// Destroy method. Implementing <see cref="IPooledObjectPolicy{T}"/> directly is sufficient.
/// </remarks>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
public
interface IPooledObjectDestroyPolicy<T> : IPooledObjectPolicy<T>
    where T : class
{
}
