// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Provides pools of reusable <see cref="List{T}"/> instances.</summary>
/// <typeparam name="T">The element type.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class ListPool<T>
{
    private readonly ObjectPool<List<T>, Policy> _pool;
    private InstanceThreadLocalFrontTier<List<T>> _scopedTier;

    /// <summary>Gets the default largest list capacity retained by a pool.</summary>
    public const int DefaultMaximumRetainedCapacity = 1024;

    /// <summary>Gets the shared pool.</summary>
    public static ListPool<T> Shared { get; } = new();

    /// <summary>
    /// Gets an opt-in pool that retains one list per participating thread before using
    /// <see cref="Shared"/> as a bounded fallback.
    /// </summary>
    public static ThreadLocalPool ThreadLocalShared { get; } = new();

    /// <summary>Initializes a pool with default limits.</summary>
    public ListPool()
        : this(DefaultMaximumRetainedCapacity, ObjectPool<List<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom maximum retained list capacity.</summary>
    public ListPool(int maxRetainedCapacity)
        : this(maxRetainedCapacity, ObjectPool<List<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with custom item and list capacity limits.</summary>
    public ListPool(int maxRetainedCapacity, int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegative(maxRetainedCapacity);
#else
        if (maxRetainedCapacity < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(maxRetainedCapacity),
                maxRetainedCapacity,
                null);
        }
#endif
        MaximumRetainedCapacity = maxRetainedCapacity;
        _pool = new ObjectPool<List<T>, Policy>(new Policy(maxRetainedCapacity), maxCapacity);
    }

    /// <summary>Gets the maximum number of lists retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets the largest list capacity retained by this pool.</summary>
    public int MaximumRetainedCapacity { get; }

    /// <summary>Rents an empty list.</summary>
    public List<T> Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Rents an empty list owned by a stack-only thread-local lease.</summary>
    public Lease RentScoped()
        => new(this, _scopedTier.Rent(_pool));

    /// <summary>
    /// Rents an empty list owned by a stack-only thread-local lease and exposes it directly.
    /// </summary>
    public Lease RentScoped(out List<T> list)
    {
        list = _scopedTier.Rent(_pool);
        return new Lease(this, list);
    }

    /// <summary>Returns a list, clearing it when retained and discarding it when too large.</summary>
    public void Return(List<T> list)
    {
        ThrowIfNull(list);

        if (!TryReset(list))
        {
            return;
        }

        _pool.ReturnWithoutReset(list);
    }

    private bool TryReset(List<T> list)
    {
        if (Policy.Reset(list, MaximumRetainedCapacity))
        {
            return true;
        }

        _pool.Destroy(list);
        return false;
    }

    private void ReturnScoped(List<T> list)
    {
        if (!TryReset(list))
        {
            return;
        }

        if (!_scopedTier.TryReturn(list))
        {
            _pool.ReturnWithoutReset(list);
        }
    }

    private static void ThrowIfNull(List<T>? list)
    {
        if (list is null)
        {
            throw new ArgumentNullException("obj");
        }
    }

    private readonly struct Policy(int maxRetainedCapacity) : IPooledObjectPolicy<List<T>>
    {
        public List<T> Create() => [];

        internal static bool Reset(List<T> obj, int maximumRetainedCapacity)
        {
            if (obj.Capacity > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
        }

        public bool TryReset(List<T> obj) => Reset(obj, maxRetainedCapacity);

        // Mirrors the interface default method; the explicit implementation keeps the constrained
        // Destroy call devirtualized instead of boxing this struct on every discarded object.
        public void Destroy(List<T> obj)
        {
            if (obj is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }

    /// <summary>Owns a thread-local list rental and returns it when disposed.</summary>
    public ref struct Lease
    {
        private readonly ListPool<T>? _pool;
        private ScopedPoolLease<List<T>> _lease;

        internal Lease(ListPool<T> pool, List<T> list)
        {
            _pool = pool;
            _lease = new ScopedPoolLease<List<T>>(list);
        }

        /// <summary>Gets the rented list while this lease owns it.</summary>
        public readonly List<T> Value => _lease.Value;

        /// <summary>Returns the list. Repeated calls and stale copies are ignored.</summary>
        public void Dispose()
        {
            if (_lease.TryRelease(out List<T> list))
            {
                _pool!.ReturnScoped(list);
            }
        }
    }

    /// <summary>Provides thread-local-first access to <see cref="Shared"/>.</summary>
    public sealed class ThreadLocalPool
    {
        internal ThreadLocalPool()
        {
        }

        /// <summary>Rents an empty list from the current thread or shared fallback.</summary>
        public List<T> Rent()
            => ThreadLocalFrontTier<List<T>, Policy>.Rent(Shared._pool);

        /// <summary>Returns a list to the current thread or shared fallback.</summary>
        public void Return(List<T> list)
        {
            ThrowIfNull(list);
            if (!Shared.TryReset(list))
            {
                return;
            }

            if (!ThreadLocalFrontTier<List<T>, Policy>.TryReturn(list))
            {
                Shared._pool.ReturnWithoutReset(list);
            }
        }
    }
}
