// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>
/// A thread-safe object pool for callers that prefer a policy instance or factory, with bounded
/// shared retention and a per-pool thread-local tier for scoped rentals.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class ObjectPool<T> : IDisposable
    where T : class
{
    private readonly ObjectPool<T, PolicyAdapter> _pool;

    /// <summary>Initializes a pool backed by a policy instance and default capacity.</summary>
    public ObjectPool(IPooledObjectPolicy<T> policy)
        : this(policy, ObjectPool<T, PolicyAdapter>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool backed by a policy instance.</summary>
    public ObjectPool(IPooledObjectPolicy<T> policy, int maxCapacity)
    {
#if NET6_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(policy);
#else
        if (policy is null)
        {
            throw new ArgumentNullException(nameof(policy));
        }
#endif
        _pool = new ObjectPool<T, PolicyAdapter>(new PolicyAdapter(policy), maxCapacity);
    }

    /// <summary>Initializes a pool backed by a factory and default capacity.</summary>
    public ObjectPool(Func<T> factory)
        : this(factory, ObjectPool<T, PolicyAdapter>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool backed by a factory.</summary>
    public ObjectPool(Func<T> factory, int maxCapacity)
    {
#if NET6_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(factory);
#else
        if (factory is null)
        {
            throw new ArgumentNullException(nameof(factory));
        }
#endif
        _pool = new ObjectPool<T, PolicyAdapter>(new PolicyAdapter(factory), maxCapacity);
    }

    /// <summary>Gets the default maximum number of objects retained by the shared tier.</summary>
    public static int DefaultMaximumRetained => ObjectPool<T, PolicyAdapter>.DefaultMaximumRetained;

    /// <summary>Gets the maximum number of objects retained by the bounded shared tier.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Rents an object, creating one when no retained object is available.</summary>
    public T Rent() => _pool.Rent();

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path.
    /// </summary>
    public PooledLease<T> RentScoped()
    {
        T value = _pool.RentScopedValue();
        return new PooledLease<T>(_pool, value);
    }

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path and also
    /// exposes the object directly.
    /// </summary>
    public PooledLease<T> RentScoped(out T value)
    {
        value = _pool.RentScopedValue();
        return new PooledLease<T>(_pool, value);
    }

    /// <summary>Resets and returns an object. Objects exceeding capacity are discarded.</summary>
    public void Return(T obj) => _pool.Return(obj);

    /// <summary>
    /// Removes all thread-local and shared retained objects and disposes those that implement
    /// <see cref="IDisposable"/>. The pool remains usable.
    /// </summary>
    public void Clear() => _pool.Clear();

    /// <summary>
    /// Permanently closes the pool and disposes all retained disposable objects. Objects returned
    /// after disposal are disposed instead of retained.
    /// </summary>
    public void Dispose() => _pool.Dispose();

    internal readonly struct PolicyAdapter : IPooledObjectDestroyPolicy<T>
    {
        private readonly Func<T>? _factory;
        private readonly IPooledObjectPolicy<T>? _policy;

        internal PolicyAdapter(Func<T> factory)
        {
            _factory = factory;
            _policy = null;
        }

        internal PolicyAdapter(IPooledObjectPolicy<T> policy)
        {
            _factory = null;
            _policy = policy;
        }

        public T Create() => _policy is null ? _factory!() : _policy.Create();

        public bool TryReset(T obj) => _policy?.TryReset(obj) ?? true;

        public void Destroy(T obj)
        {
#if NETCOREAPP3_0_OR_GREATER
            if (_policy is not null)
            {
                _policy.Destroy(obj);
            }
#else
            if (_policy is IPooledObjectDestroyPolicy<T> destroyPolicy)
            {
                destroyPolicy.Destroy(obj);
            }
#endif
            else if (obj is IDisposable disposable)
            {
                disposable.Dispose();
            }
        }
    }
}
