// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;

namespace Reservoir;

/// <summary>
/// A thread-safe object pool specialized for a struct policy, with bounded shared retention and a
/// per-pool thread-local tier for scoped rentals.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class ObjectPool<T, TPolicy> : IDisposable, IScopedPool<T>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    // One logical slot per 64-byte cache line on 64-bit runtimes.
    private const int CacheLineSlotStride = 8;
    // Bound the cache-line store to 4 KiB and a 64-slot worst-case scan.
    private const int MaximumCacheLineSlotCapacity = 64;
    private const uint StripeHashMultiplier = 2_654_435_769u;

    // Cache only scalar affinity; retained objects remain enumerable in the shared array.
    [ThreadStatic]
    private static int _threadStripe;

    private static int s_nextThreadStripe;

#if !NETCOREAPP3_0_OR_GREATER
    private static readonly bool s_hasCustomDestroy
        = typeof(IPooledObjectDestroyPolicy<T>).IsAssignableFrom(typeof(TPolicy));
    private static readonly bool s_isStaticallyDisposable
        = typeof(IDisposable).IsAssignableFrom(typeof(T));

    private static readonly bool s_mayHaveDisposableImplementations = !typeof(T).IsSealed;
#endif

    private readonly ObjectWrapper[] _items;
    private readonly int _indexMask;
    private readonly StripedObjectStore<T>? _largeStore;
    private TrackedInstanceThreadLocalFrontTier<T> _scopedTier;
    private TPolicy _policy;
    private int _isDisposed;

    /// <summary>Initializes a pool with the default policy value and capacity.</summary>
    public ObjectPool()
        : this(default, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the default policy value.</summary>
    public ObjectPool(int maxCapacity)
        : this(default, maxCapacity)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and default capacity.</summary>
    public ObjectPool(TPolicy policy)
        : this(policy, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and capacity.</summary>
    public ObjectPool(TPolicy policy, int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(maxCapacity);
#else
        if (maxCapacity <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(maxCapacity), maxCapacity, null);
        }
#endif

        _policy = policy;
        MaximumRetained = maxCapacity;
#if NET8_0_OR_GREATER
        _indexMask = BitOperations.IsPow2((uint)maxCapacity) ? maxCapacity - 1 : -1;
#else
        _indexMask = (maxCapacity & (maxCapacity - 1)) == 0 ? maxCapacity - 1 : -1;
#endif
        if (maxCapacity <= MaximumCacheLineSlotCapacity)
        {
            _items = new ObjectWrapper[checked(maxCapacity * CacheLineSlotStride)];
        }
        else
        {
            _items = Array.Empty<ObjectWrapper>();
            _largeStore = new StripedObjectStore<T>(maxCapacity);
        }
    }

    /// <summary>Gets the default maximum number of objects retained by the shared tier.</summary>
    public static int DefaultMaximumRetained => Math.Max(32, 2 * Environment.ProcessorCount);

    /// <summary>Gets the maximum number of objects retained by the bounded shared tier.</summary>
    public int MaximumRetained { get; }

    /// <summary>Rents an object, creating one when no retained object is available.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T Rent()
    {
        ThrowIfDisposed();

        T rented = RentWithoutLifecycle();

        if (Volatile.Read(ref _isDisposed) == 0)
        {
            return rented;
        }

        DisposeItem(rented);
        return ThrowDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T RentWithoutLifecycle()
    {
        StripedObjectStore<T>? largeStore = _largeStore;
        int startIndex = 0;
        T? item;

        if (largeStore is null)
        {
            startIndex = GetStartIndex();
            ref T? startSlot = ref GetSlot(startIndex);
            T? observed = Volatile.Read(ref startSlot);
            // A failed CAS is a permitted pool miss; RentSlow scans the remaining slots.
            item = observed is not null
                && ReferenceEquals(
                    Interlocked.CompareExchange(ref startSlot, null, observed),
                    observed)
                ? observed
                : null;
        }
        else
        {
            _ = largeStore.TryPop(out item);
        }

        return item
            ?? (largeStore is null
                ? RentSlow(startIndex)
                : CreateItem());
    }

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public PooledLease<T, TPolicy> RentScoped()
    {
        T value = RentScopedValue();
        return new PooledLease<T, TPolicy>(this, value);
    }

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path and also
    /// exposes the object directly.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public PooledLease<T, TPolicy> RentScoped(out T value)
    {
        value = RentScopedValue();
        return new PooledLease<T, TPolicy>(this, value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T RentScopedValue()
    {
        ThrowIfDisposed();
        T value = _scopedTier.Rent(this);
        if (Volatile.Read(ref _isDisposed) == 0)
        {
            return value;
        }

        DisposeItem(value);
        return ThrowDisposed();
    }

    void IScopedPool<T>.ReturnScoped(T value)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!TryResetItem(value))
        {
            DisposeItem(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!_scopedTier.TryReturn(value))
        {
            ReturnWithoutResetWithLifecycle(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0 && _scopedTier.TryRemove(value))
        {
            DisposeItem(value);
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private T RentSlow(int startIndex)
    {
        for (int offset = 1; offset < MaximumRetained; offset++)
        {
            int index = startIndex + offset;
            if (index >= MaximumRetained)
            {
                index -= MaximumRetained;
            }

            ref T? slot = ref GetSlot(index);
            T? item = Volatile.Read(ref slot);
            if (item is not null
                && ReferenceEquals(
                    Interlocked.CompareExchange(ref slot, null, item),
                    item))
            {
                return item;
            }
        }

        return CreateItem();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private T CreateItem()
        => _policy.Create()
            ?? throw new InvalidOperationException("The pool policy returned null from Create().");

    /// <summary>Resets and returns an object. Objects exceeding capacity are discarded.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Return(T obj)
    {
#if NET6_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(obj);
#else
        if (obj is null)
        {
            throw new ArgumentNullException(nameof(obj));
        }
#endif

        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(obj);
            return;
        }

        if (!TryResetItem(obj))
        {
            DisposeItem(obj);
            return;
        }

        ReturnWithoutReset(obj);
        ClearIfDisposed();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private bool TryResetItem(T obj)
    {
        try
        {
            return _policy.TryReset(obj);
        }
        catch
        {
            DisposeItem(obj);
            throw;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ReturnWithoutReset(T obj)
    {
        StripedObjectStore<T>? largeStore = _largeStore;
        if (largeStore is not null)
        {
            if (!largeStore.TryPush(obj))
            {
                DisposeItem(obj);
            }

            return;
        }

        int startIndex = GetStartIndex();
        ref T? startSlot = ref GetSlot(startIndex);
        T? displaced = Interlocked.Exchange(ref startSlot, obj);
        if (displaced is null)
        {
            return;
        }

        ReturnSlow(obj, displaced, startIndex);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ReturnWithoutResetWithLifecycle(T obj)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(obj);
            return;
        }

        ReturnWithoutReset(obj);
        ClearIfDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void Destroy(T obj) => DisposeItem(obj);

    /// <summary>
    /// Removes all thread-local and shared retained objects and disposes those that implement
    /// <see cref="IDisposable"/>. The pool remains usable.
    /// </summary>
    public void Clear()
    {
        Exception? firstException = null;
        try
        {
            _scopedTier.Clear(this);
        }
        catch (Exception exception)
        {
            firstException = exception;
        }

        StripedObjectStore<T>? largeStore = _largeStore;
        if (largeStore is not null)
        {
            while (largeStore.TryPop(out T? item))
            {
                DisposeRetained(item, ref firstException);
            }

            if (firstException is not null)
            {
                ExceptionDispatchInfo.Capture(firstException).Throw();
            }

            return;
        }

        for (int i = 0; i < MaximumRetained; i++)
        {
            DisposeRetained(
                Interlocked.Exchange(ref GetSlot(i), null),
                ref firstException);
        }

        if (firstException is not null)
        {
            ExceptionDispatchInfo.Capture(firstException).Throw();
        }
    }

    /// <summary>
    /// Permanently closes the pool and disposes all retained disposable objects. Objects returned
    /// after disposal are disposed instead of retained.
    /// </summary>
    public void Dispose()
    {
        if (Interlocked.Exchange(ref _isDisposed, 1) == 0)
        {
            Clear();
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private void ReturnSlow(T returned, T displaced, int startIndex)
    {
        for (int offset = 1; offset < MaximumRetained; offset++)
        {
            int index = startIndex + offset;
            if (index >= MaximumRetained)
            {
                index -= MaximumRetained;
            }

            if (Interlocked.CompareExchange(ref GetSlot(index), displaced, null) is null)
            {
                return;
            }
        }

        // Preserve full-pool semantics: discard the newly returned object when
        // it has not already been rented or displaced by another thread.
        T? observed = Interlocked.CompareExchange(
            ref GetSlot(startIndex),
            displaced,
            returned);
        DisposeItem(ReferenceEquals(observed, returned) ? returned : displaced);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetStartIndex()
    {
        int threadStripe = _threadStripe;
        if (threadStripe == 0)
        {
            do
            {
                threadStripe = Interlocked.Increment(ref s_nextThreadStripe);
            }
            while (threadStripe == 0);

            _threadStripe = threadStripe;
        }

        return GetAffinityIndex(unchecked((uint)(threadStripe - 1)));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal int GetAffinityIndex(uint threadStripe)
    {
        uint mixedStripe = threadStripe * StripeHashMultiplier;
        // Preserve masking for powers of two; scale other hashes without integer division.
        return _indexMask >= 0
            ? (int)(mixedStripe & (uint)_indexMask)
            : (int)(((ulong)mixedStripe * (uint)MaximumRetained) >> 32);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref T? GetSlot(int index)
        => ref _items[index * CacheLineSlotStride].Element;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ClearIfDisposed()
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            Clear();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ThrowIfDisposed()
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            ThrowDisposed();
        }
    }

#if NET5_0_OR_GREATER
    [DoesNotReturn]
#endif
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T ThrowDisposed()
        => throw new ObjectDisposedException(typeof(ObjectPool<T, TPolicy>).FullName);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void DisposeItem(T obj)
    {
#if NETCOREAPP3_0_OR_GREATER
        _policy.Destroy(obj);
#else
        if (s_hasCustomDestroy)
        {
            ((IPooledObjectDestroyPolicy<T>)(object)_policy).Destroy(obj);
            return;
        }

        DefaultDestroy(obj);
#endif
    }

#if !NETCOREAPP3_0_OR_GREATER
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static void DefaultDestroy(T obj)
    {
        if (s_isStaticallyDisposable)
        {
            ((IDisposable)obj).Dispose();
            return;
        }

        if (s_mayHaveDisposableImplementations && obj is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
#endif

    private void DisposeRetained(T? obj, ref Exception? firstException)
    {
        if (obj is null)
        {
            return;
        }

        try
        {
            DisposeItem(obj);
        }
        catch (Exception exception)
        {
            firstException ??= exception;
        }
    }

    private struct ObjectWrapper
    {
        internal T? Element;
    }
}
