// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;

namespace Reservoir;

/// <summary>
/// A thread-safe object pool specialized for a struct policy, with bounded shared retention and a
/// per-pool thread-local tier for default scoped rentals.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class ObjectPool<T, TPolicy> : IDisposable
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    // One logical slot per 64-byte cache line on 64-bit runtimes.
    private const int CacheLineSlotStride = 8;
    // The first slot starts one stride in so that no slot shares a cache line with the array
    // header, whose length every bounds check reads.
    private const int FirstSlotOffset = CacheLineSlotStride;
    // Bound the cache-line store to 4 KiB plus the header line and a 64-slot worst-case scan.
    private const int MaximumCacheLineSlotCapacity = 64;
    private const uint StripeHashMultiplier = 2_654_435_769u;

    // Cache only scalar affinity; retained objects remain enumerable in the shared array.
    [ThreadStatic]
    private static int _threadStripe;

    private static int s_nextThreadStripe;

    private readonly ObjectWrapper[] _items;
    private readonly int _indexMask;
    private readonly bool _threadLocalFastPath;
#if NET10_0_OR_GREATER
    private readonly bool _skipReset;
#endif
    private readonly StripedObjectStore<T>? _largeStore;
    private TrackedInstanceThreadLocalFrontTier<T> _scopedTier;
    private TPolicy _policy;
    private int _isDisposed;

    /// <summary>Initializes a pool with the default policy value and capacity.</summary>
    public ObjectPool()
        : this(default, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the default policy value.</summary>
    public ObjectPool(int maxCapacity)
        : this(default, maxCapacity)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and default capacity.</summary>
    public ObjectPool(TPolicy policy)
        : this(policy, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and capacity.</summary>
    /// <remarks>
    /// The thread-local fast path is disabled by default, so retention is bounded strictly to
    /// <see cref="MaximumRetained"/>. Use
    /// <see cref="ObjectPool{T,TPolicy}(TPolicy, int, bool)"/> to opt in when same-thread reuse
    /// outweighs the lookup overhead and additional per-thread retention.
    /// </remarks>
    public ObjectPool(TPolicy policy, int maxCapacity)
    {
        _threadLocalFastPath = false;
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegativeOrZero(maxCapacity);
#else
        if (maxCapacity <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(maxCapacity), maxCapacity, null);
        }
#endif

        _policy = policy;
        MaximumRetained = maxCapacity;
#if NET8_0_OR_GREATER
        _indexMask = BitOperations.IsPow2((uint)maxCapacity) ? maxCapacity - 1 : -1;
#else
        _indexMask = (maxCapacity & (maxCapacity - 1)) == 0 ? maxCapacity - 1 : -1;
#endif
        if (maxCapacity <= MaximumCacheLineSlotCapacity)
        {
            _items = new ObjectWrapper[checked(FirstSlotOffset + maxCapacity * CacheLineSlotStride)];
        }
        else
        {
            _items = Array.Empty<ObjectWrapper>();
            _largeStore = new StripedObjectStore<T>(maxCapacity);
        }
    }

    /// <summary>
    /// Initializes a pool with the supplied policy and capacity, controlling whether
    /// <see cref="Rent()"/> and <see cref="Return"/> use the per-pool thread-local tier.
    /// </summary>
    /// <remarks>
    /// With the fast path enabled, a rent takes the current thread's slot when it holds an object,
    /// and a return stores into the returning thread's slot when that thread has rented from this
    /// pool and the slot is empty, overflowing to the bounded shared tier otherwise — so each
    /// thread that rents retains up to one object beyond <see cref="MaximumRetained"/> until it
    /// rents again or <see cref="Clear"/> or <see cref="Dispose"/> runs. A thread that only
    /// returns (a completion or IO thread receiving handed-off objects) never parks one. Same-
    /// thread reuse costs a single atomic operation. Pass <see langword="true"/> to opt in.
    /// </remarks>
    public ObjectPool(TPolicy policy, int maxCapacity, bool threadLocalFastPath)
        : this(policy, maxCapacity)
    {
        _threadLocalFastPath = threadLocalFastPath;
    }

#if NET10_0_OR_GREATER
    // Factory-backed pools have no reset callback. Preserve lifecycle checks while avoiding
    // the guarded reset call on every return, including returns carried by scoped leases.
    internal ObjectPool(TPolicy policy, int maxCapacity, bool threadLocalFastPath, bool skipReset)
        : this(policy, maxCapacity, threadLocalFastPath)
    {
        _skipReset = skipReset;
    }
#endif

    /// <summary>Gets the default maximum number of objects retained by the shared tier.</summary>
    public static int DefaultMaximumRetained => Math.Max(32, 2 * Environment.ProcessorCount);

    /// <summary>Gets the maximum number of objects retained by the bounded shared tier.</summary>
    public int MaximumRetained { get; }

    /// <summary>Rents an object, creating one when no retained object is available.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T Rent()
    {
        if (_threadLocalFastPath)
        {
            return RentScopedValue(out _);
        }

        ThrowIfDisposed();

        T rented = RentWithoutLifecycle();

        if (Volatile.Read(ref _isDisposed) == 0)
        {
            return rented;
        }

        DisposeItem(rented);
        return ThrowDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T RentWithoutLifecycle()
    {
        StripedObjectStore<T>? largeStore = _largeStore;
        int startIndex = 0;
        T? item;

        if (largeStore is null)
        {
            startIndex = GetStartIndex();
            ref T? startSlot = ref GetSlot(startIndex);
            T? observed = Volatile.Read(ref startSlot);
            // A failed CAS is a permitted pool miss; RentSlow scans the remaining slots.
            item = observed is not null
                && ReferenceEquals(
                    Interlocked.CompareExchange(ref startSlot, null, observed),
                    observed)
                ? observed
                : null;
        }
        else
        {
            _ = largeStore.TryPop(out item);
        }

        return item
            ?? (largeStore is null
                ? RentSlow(startIndex)
                : CreateItem());
    }

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public PooledLease<T, TPolicy> RentScoped()
    {
        T value = RentScopedValue(out TrackedInstanceThreadLocalFrontTier<T>.Slot slot);
        return new PooledLease<T, TPolicy>(this, value, slot);
    }

    /// <summary>
    /// Rents an object owned by a stack-only lease using a per-pool thread-local fast path and also
    /// exposes the object directly.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public PooledLease<T, TPolicy> RentScoped(out T value)
    {
        value = RentScopedValue(out TrackedInstanceThreadLocalFrontTier<T>.Slot slot);
        return new PooledLease<T, TPolicy>(this, value, slot);
    }

    /// <summary>
    /// Rents a stack-only lease whose idle object returns only to the bounded shared store.
    /// </summary>
    /// <remarks>
    /// This mode bypasses thread-local object retention, including when manual rentals opt into
    /// that tier. The bound applies to idle pooled objects, not outstanding rentals or lease
    /// ownership bookkeeping. Other rental modes can still retain thread-local objects.
    /// </remarks>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public SharedPooledLease<T, TPolicy> RentScopedShared()
        => new(this, RentSharedValue());

    /// <summary>
    /// Rents a shared-store scoped lease and exposes its object directly.
    /// </summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public SharedPooledLease<T, TPolicy> RentScopedShared(out T value)
    {
        value = RentSharedValue();
        return new SharedPooledLease<T, TPolicy>(this, value);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T RentSharedValue()
    {
        ThrowIfDisposed();
        T value = RentWithoutLifecycle();
        if (Volatile.Read(ref _isDisposed) == 0)
        {
            return value;
        }

        DisposeItem(value);
        return ThrowDisposed();
    }

    // Shared-store leases bypass the manual TLS option on both rent and return.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ReturnSharedValue(T value)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!TryResetItem(value))
        {
            DisposeItem(value);
            return;
        }

        ReturnWithoutReset(value);
        ClearIfDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T RentScopedValue(out TrackedInstanceThreadLocalFrontTier<T>.Slot slot)
    {
        ThrowIfDisposed();
        T value = _scopedTier.Rent(this, out slot);
        if (Volatile.Read(ref _isDisposed) == 0)
        {
            return value;
        }

        DisposeItem(value);
        return ThrowDisposed();
    }

    // The slot rented with the value replaces the return-side thread-local lookup; a stack-only
    // lease cannot change threads, so it is still the returning thread's own slot.
    internal void ReturnScoped(T value, TrackedInstanceThreadLocalFrontTier<T>.Slot slot)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!TryResetItem(value))
        {
            DisposeItem(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!TrackedInstanceThreadLocalFrontTier<T>.TryReturn(slot, value))
        {
            ReturnWithoutResetWithLifecycle(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0
            && TrackedInstanceThreadLocalFrontTier<T>.TryRemove(slot, value))
        {
            DisposeItem(value);
        }
    }

    // The fast-path Return has no lease to carry the slot, so this overload resolves the
    // returning thread's slot through the tier.
    internal void ReturnScoped(T value)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!TryResetItem(value))
        {
            DisposeItem(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(value);
            return;
        }

        if (!_scopedTier.TryReturn(value))
        {
            ReturnWithoutResetWithLifecycle(value);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0 && _scopedTier.TryRemove(value))
        {
            DisposeItem(value);
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private T RentSlow(int startIndex)
    {
        ObjectWrapper[] items = _items;
        int startSlot = FirstSlotOffset + startIndex * CacheLineSlotStride;
        // Scan physical indices in two contiguous ranges. The home slot was already tried;
        // splitting at the array boundary avoids wrap arithmetic on every empty slot.
        for (int index = startSlot + CacheLineSlotStride; index < items.Length; index += CacheLineSlotStride)
        {
            ref T? slot = ref items[index].Element;
            T? item = Volatile.Read(ref slot);
            if (item is not null
                && ReferenceEquals(
                    Interlocked.CompareExchange(ref slot, null, item),
                    item))
            {
                return item;
            }
        }

        for (int index = FirstSlotOffset; index < startSlot; index += CacheLineSlotStride)
        {
            ref T? slot = ref items[index].Element;
            T? item = Volatile.Read(ref slot);
            if (item is not null
                && ReferenceEquals(
                    Interlocked.CompareExchange(ref slot, null, item),
                    item))
            {
                return item;
            }
        }

        return CreateItem();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private T CreateItem()
        => _policy.Create()
            ?? throw new InvalidOperationException("The pool policy returned null from Create().");

    /// <summary>Resets and returns an object. Objects exceeding capacity are discarded.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Return(T obj)
    {
#if NET6_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(obj);
#else
        if (obj is null)
        {
            throw new ArgumentNullException(nameof(obj));
        }
#endif

        if (_threadLocalFastPath)
        {
            ReturnScoped(obj);
            return;
        }

        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(obj);
            return;
        }

        if (!TryResetItem(obj))
        {
            DisposeItem(obj);
            return;
        }

        ReturnWithoutReset(obj);
        ClearIfDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool TryResetItem(T obj)
    {
#if NET10_0_OR_GREATER
        // Only the runtime adapter can use factory mode. Other struct policies fold this
        // type test away and keep their existing return path without another field read.
        if (typeof(TPolicy) == typeof(ObjectPool<T>.PolicyAdapter) && _skipReset)
        {
            return true;
        }
#endif

        // The type test folds to a constant per instantiation, so marked policies reset inline
        // while unmarked policies keep the out-of-line destroy-on-throw wrapper.
        if (default(TPolicy) is INonThrowingResetPolicy)
        {
            return _policy.TryReset(obj);
        }

        return TryResetItemGuarded(obj);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private bool TryResetItemGuarded(T obj)
    {
        try
        {
            return _policy.TryReset(obj);
        }
        catch (Exception resetException)
        {
            try
            {
                DisposeItem(obj);
            }
            catch (Exception destroyException)
            {
                throw new AggregateException(
                    "Reset and destruction both failed.", resetException, destroyException);
            }

            throw;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ReturnWithoutReset(T obj)
    {
        StripedObjectStore<T>? largeStore = _largeStore;
        if (largeStore is not null)
        {
            if (!largeStore.TryPush(obj))
            {
                DisposeItem(obj);
            }

            return;
        }

        int startIndex = GetStartIndex();
        ref T? startSlot = ref GetSlot(startIndex);
        T? displaced = Interlocked.Exchange(ref startSlot, obj);
        if (displaced is null)
        {
            return;
        }

        ReturnSlow(obj, displaced, startIndex);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ReturnWithoutResetWithLifecycle(T obj)
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            DisposeItem(obj);
            return;
        }

        ReturnWithoutReset(obj);
        ClearIfDisposed();
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void Destroy(T obj) => DisposeItem(obj);

    /// <summary>
    /// Removes all thread-local and shared retained objects and disposes those that implement
    /// <see cref="IDisposable"/>. The pool remains usable.
    /// </summary>
    public void Clear()
    {
        Exception? firstException = null;
        try
        {
            _scopedTier.Clear(this);
        }
        catch (Exception exception)
        {
            firstException = exception;
        }

        StripedObjectStore<T>? largeStore = _largeStore;
        if (largeStore is not null)
        {
            while (largeStore.TryPop(out T? item))
            {
                DisposeRetained(item, ref firstException);
            }

            if (firstException is not null)
            {
                ExceptionDispatchInfo.Capture(firstException).Throw();
            }

            return;
        }

        for (int i = 0; i < MaximumRetained; i++)
        {
            DisposeRetained(
                Interlocked.Exchange(ref GetSlot(i), null),
                ref firstException);
        }

        if (firstException is not null)
        {
            ExceptionDispatchInfo.Capture(firstException).Throw();
        }
    }

    /// <summary>
    /// Permanently closes the pool and disposes all retained disposable objects. Objects returned
    /// after disposal are disposed instead of retained.
    /// </summary>
    public void Dispose()
    {
        if (Interlocked.Exchange(ref _isDisposed, 1) == 0)
        {
            Clear();
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private void ReturnSlow(T returned, T displaced, int startIndex)
    {
        ObjectWrapper[] items = _items;
        int startSlot = FirstSlotOffset + startIndex * CacheLineSlotStride;
        for (int index = startSlot + CacheLineSlotStride; index < items.Length; index += CacheLineSlotStride)
        {
            // Occupied slots cost a shared read, preserving read-before-CAS under contention.
            ref T? slot = ref items[index].Element;
            if (Volatile.Read(ref slot) is null
                && Interlocked.CompareExchange(ref slot, displaced, null) is null)
            {
                return;
            }
        }

        for (int index = FirstSlotOffset; index < startSlot; index += CacheLineSlotStride)
        {
            ref T? slot = ref items[index].Element;
            if (Volatile.Read(ref slot) is null
                && Interlocked.CompareExchange(ref slot, displaced, null) is null)
            {
                return;
            }
        }

        // Preserve full-pool semantics: discard the newly returned object when
        // it has not already been rented or displaced by another thread.
        T? observed = Interlocked.CompareExchange(
            ref items[startSlot].Element,
            displaced,
            returned);
        DisposeItem(ReferenceEquals(observed, returned) ? returned : displaced);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetStartIndex()
    {
        int threadStripe = _threadStripe;
        if (threadStripe == 0)
        {
            do
            {
                threadStripe = Interlocked.Increment(ref s_nextThreadStripe);
            }
            while (threadStripe == 0);

            _threadStripe = threadStripe;
        }

        return GetAffinityIndex(unchecked((uint)(threadStripe - 1)));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal int GetAffinityIndex(uint threadStripe)
    {
        uint mixedStripe = threadStripe * StripeHashMultiplier;
        // Preserve masking for powers of two; scale other hashes without integer division.
        return _indexMask >= 0
            ? (int)(mixedStripe & (uint)_indexMask)
            : (int)(((ulong)mixedStripe * (uint)MaximumRetained) >> 32);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private ref T? GetSlot(int index)
        => ref _items[FirstSlotOffset + index * CacheLineSlotStride].Element;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ClearIfDisposed()
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            Clear();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void ThrowIfDisposed()
    {
        if (Volatile.Read(ref _isDisposed) != 0)
        {
            ThrowDisposed();
        }
    }

#if NET5_0_OR_GREATER
    [DoesNotReturn]
#endif
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T ThrowDisposed()
        => throw new ObjectDisposedException(typeof(ObjectPool<T, TPolicy>).FullName);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private void DisposeItem(T obj)
        => _policy.Destroy(obj);

    private void DisposeRetained(T? obj, ref Exception? firstException)
    {
        if (obj is null)
        {
            return;
        }

        try
        {
            DisposeItem(obj);
        }
        catch (Exception exception)
        {
            firstException ??= exception;
        }
    }

    private struct ObjectWrapper
    {
        internal T? Element;
    }
}
