// <auto-generated/>
#if DEBUG || RESERVOIR_DIAGNOSTICS
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Reports objects that became unreachable without being returned to their pool.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
static class ObjectPoolDiagnostics
{
    /// <summary>
    /// Raised from the finalizer thread when an outstanding rental becomes unreachable.
    /// Subscribers must return quickly and must not throw.
    /// </summary>
    public static event Action<string>? LeakDetected;

    internal static void ReportLeak(Type objectType, string rentSite)
    {
        string message =
            $"A pooled {objectType.FullName} was garbage collected without being returned."
            + $"{Environment.NewLine}Rent site:{Environment.NewLine}{rentSite}";

        Trace.TraceError(message);

        Delegate[] handlers = LeakDetected?.GetInvocationList() ?? [];
        foreach (Delegate handler in handlers)
        {
            try
            {
                ((Action<string>)handler)(message);
            }
            catch
            {
                // User diagnostics must never terminate the finalizer thread.
            }
        }
    }
}
#endif
