// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Threading;

namespace Reservoir;

/// <summary>Configures invalid-return and leaked-rental diagnostics for object pools.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
static class ObjectPoolDiagnostics
{
    private static int s_enabled;

    /// <summary>
    /// Gets or sets whether newly created pools track invalid returns and leaked rentals.
    /// Existing pools keep the setting captured when they were created.
    /// </summary>
    public static bool Enabled
    {
        get => Volatile.Read(ref s_enabled) != 0;
        set => Volatile.Write(ref s_enabled, value ? 1 : 0);
    }

    /// <summary>Enables diagnostics when called from a Debug consumer build.</summary>
    [Conditional("DEBUG")]
    public static void EnableForDebugBuilds() => Enabled = true;

    /// <summary>
    /// Raised from the finalizer thread when an outstanding rental becomes unreachable.
    /// Subscribers must return quickly and must not throw.
    /// </summary>
    public static event Action<string>? LeakDetected;

    internal static void ReportLeak(Type objectType, string rentSite)
    {
        string message =
            $"A pooled {objectType.FullName} was garbage collected without being returned."
            + $"{Environment.NewLine}Rent site:{Environment.NewLine}{rentSite}";

        try
        {
            Trace.TraceError(message);
        }
        catch
        {
            // Trace listeners must never terminate the finalizer thread.
        }

        Delegate[] handlers = LeakDetected?.GetInvocationList() ?? [];
        foreach (Delegate handler in handlers)
        {
            try
            {
                ((Action<string>)handler)(message);
            }
            catch
            {
                // User diagnostics must never terminate the finalizer thread.
            }
        }
    }
}
