// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

/// <summary>
/// A thread-safe object pool specialized for application-lifetime use. This pool cannot be cleared
/// or disposed, allowing its rent and return paths to omit lifecycle synchronization.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class PermanentObjectPool<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    private readonly ObjectPool<T, TPolicy> _pool;

    /// <summary>Initializes a pool with the default policy value and capacity.</summary>
    public PermanentObjectPool()
        : this(default, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the default policy value.</summary>
    public PermanentObjectPool(int maxCapacity)
        : this(default, maxCapacity)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and default capacity.</summary>
    public PermanentObjectPool(TPolicy policy)
        : this(policy, DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with the supplied policy and capacity.</summary>
    public PermanentObjectPool(TPolicy policy, int maxCapacity)
    {
        _pool = new ObjectPool<T, TPolicy>(policy, maxCapacity);
    }

    /// <summary>Gets the default maximum number of objects retained by the pool.</summary>
    public static int DefaultMaximumRetained => ObjectPool<T, TPolicy>.DefaultMaximumRetained;

    /// <summary>Gets the maximum number of objects retained by the pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Rents an object, creating one when no retained object is available.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public T Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Resets and returns an object. Objects exceeding capacity are destroyed.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Return(T obj)
    {
#if NET6_0_OR_GREATER
        ArgumentNullException.ThrowIfNull(obj);
#else
        if (obj is null)
        {
            throw new ArgumentNullException(nameof(obj));
        }
#endif

        if (!_pool.TryResetWithoutLifecycle(obj))
        {
            _pool.Destroy(obj);
            return;
        }

        _pool.ReturnWithoutReset(obj);
    }
}
