// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T,TPolicy}"/> and returns it on disposal.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct PooledLease<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    private readonly PooledLeaseState<T, TPolicy>? _state;
    private readonly ObjectPool<T, TPolicy> _pool;
    private readonly T _value;
    private readonly long _token;

    internal PooledLease(
        PooledLeaseState<T, TPolicy> state,
        ObjectPool<T, TPolicy> pool,
        T value,
        long token)
    {
        _state = state;
        _pool = pool;
        _value = value;
        _token = token;
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value
    {
        get
        {
            PooledLeaseState<T, TPolicy>? state = _state;
            if (state is null)
            {
                PooledLeaseThrowHelper.ThrowDisposed();
            }

            state!.ValidateOwnership(_token);
            return _value;
        }
    }

    /// <summary>Returns the rented object. Repeated calls on this lease are ignored.</summary>
    public void Dispose()
    {
        PooledLeaseState<T, TPolicy>? state = _state;

        if (state is not null && state.TryRelease(_token))
        {
            _pool.Return(_value);
        }
    }
}

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T}"/> and returns it on disposal.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct PooledLease<T>
    where T : class
{
    private PooledLease<T, ObjectPool<T>.PolicyAdapter> _lease;

    internal PooledLease(PooledLease<T, ObjectPool<T>.PolicyAdapter> lease)
    {
        _lease = lease;
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value => _lease.Value;

    /// <summary>Returns the rented object. Repeated calls on this lease are ignored.</summary>
    public void Dispose() => _lease.Dispose();
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class PooledLeaseState<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    // Thread-local slots use even versions when idle and odd versions to identify
    // active leases, so stale copies cannot release a later lease using the slot.
    private long _version;
    internal PooledLeaseState<T, TPolicy>? Next { get; set; }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryAcquire(out long token)
    {
        if ((_version & 1) != 0)
        {
            token = 0;
            return false;
        }

        token = _version + 1;
        _version = token;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ValidateOwnership(long token)
    {
        if (_version != token)
        {
            PooledLeaseThrowHelper.ThrowDisposed();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRelease(long token)
    {
        if (_version != token)
        {
            return false;
        }

        _version = token + 1;
        return true;
    }
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class PooledLeaseThrowHelper
{
#if NET5_0_OR_GREATER
    [DoesNotReturn]
#endif
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static void ThrowDisposed()
        => throw new ObjectDisposedException("PooledLease");
}
