// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T,TPolicy}"/> and returns it on disposal.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct PooledLease<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    private ScopedPoolLease<T, ObjectPool<T, TPolicy>> _lease;

    internal PooledLease(ObjectPool<T, TPolicy> pool, T value)
    {
        _lease = new ScopedPoolLease<T, ObjectPool<T, TPolicy>>(pool, value);
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value => _lease.Value;

    /// <summary>Returns the rented object. Repeated calls on this lease are ignored.</summary>
    public void Dispose() => _lease.Dispose();
}

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T}"/> and returns it on disposal.
/// </summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct PooledLease<T>
    where T : class
{
    private ScopedPoolLease<T, ObjectPool<T, ObjectPool<T>.PolicyAdapter>> _lease;

    internal PooledLease(
        ObjectPool<T, ObjectPool<T>.PolicyAdapter> pool,
        T value)
    {
        _lease = new ScopedPoolLease<
            T,
            ObjectPool<T, ObjectPool<T>.PolicyAdapter>>(pool, value);
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value => _lease.Value;

    /// <summary>Returns the rented object. Repeated calls on this lease are ignored.</summary>
    public void Dispose() => _lease.Dispose();
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class PooledLeaseThrowHelper
{
#if NET5_0_OR_GREATER
    [DoesNotReturn]
#endif
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static void ThrowDisposed()
        => throw new ObjectDisposedException("PooledLease");
}
