// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

// Internal adapters can guard callbacks themselves without claiming those callbacks never
// throw. Public policies still use INonThrowingResetPolicy only when reset cannot throw.
internal interface IHandlesResetFailure
{
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class PooledObjectPolicyReset
{
    // Pass struct policies by reference so mutable policy state stays in the owning pool.
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static bool TryReset<T, TPolicy>(ref TPolicy policy, T obj)
        where T : class
        where TPolicy : IPooledObjectPolicy<T>
    {
        try
        {
            return policy.TryReset(obj);
        }
        catch (Exception resetException)
        {
            try
            {
                policy.Destroy(obj);
            }
            catch (Exception destroyException)
            {
                throw new AggregateException(
                    "Reset and destruction both failed.", resetException, destroyException);
            }

            throw;
        }
    }
}
