// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Sources;

namespace Reservoir;

/// <summary>
/// Represents a manually completed operation that returns to its pool when consumed.
/// </summary>
/// <remarks>
/// Create one <see cref="ValueTask"/> per rental and consume it exactly once. The producer must
/// not access this source after calling <see cref="SetResult"/> or <see cref="SetException"/>.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class PooledValueTaskSource : IValueTaskSource
{
    private readonly ValueTaskSourcePool _owner;
    private ManualResetValueTaskSourceCore<bool> _core;
    private int _isConsumed;

    internal PooledValueTaskSource(
        ValueTaskSourcePool owner,
        bool runContinuationsAsynchronously)
    {
        _owner = owner;
        _core.RunContinuationsAsynchronously = runContinuationsAsynchronously;
    }

    /// <summary>Gets the token for the current rental.</summary>
    public short Version => _core.Version;

    /// <summary>Creates the single value task for the current rental.</summary>
    public ValueTask CreateValueTask() => new(this, Version);

    /// <summary>Completes the current operation successfully.</summary>
    public void SetResult() => _core.SetResult(true);

    /// <summary>Completes the current operation with an error.</summary>
    public void SetException(Exception error)
    {
        ArgumentNullException.ThrowIfNull(error);
        _core.SetException(error);
    }

    void IValueTaskSource.GetResult(short token)
    {
        ValueTaskSourceStatus status = _core.GetStatus(token);
        if (status == ValueTaskSourceStatus.Pending)
        {
            ThrowNotCompleted();
        }

        if (Interlocked.CompareExchange(ref _isConsumed, 1, 0) != 0)
        {
            ThrowAlreadyConsumed();
        }

        try
        {
            _core.GetResult(token);
        }
        finally
        {
            _core.Reset();
            Volatile.Write(ref _isConsumed, 0);
            _owner.Return(this);
        }
    }

    ValueTaskSourceStatus IValueTaskSource.GetStatus(short token) => _core.GetStatus(token);

    void IValueTaskSource.OnCompleted(
        Action<object?> continuation,
        object? state,
        short token,
        ValueTaskSourceOnCompletedFlags flags)
        => _core.OnCompleted(continuation, state, token, flags);

    [DoesNotReturn]
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void ThrowNotCompleted()
        => throw new InvalidOperationException("The operation has not yet completed.");

    [DoesNotReturn]
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void ThrowAlreadyConsumed()
        => throw new InvalidOperationException("The operation has already been consumed.");
}

/// <summary>
/// Represents a manually completed operation that returns to its pool when consumed.
/// </summary>
/// <typeparam name="T">The operation result type.</typeparam>
/// <remarks>
/// Create one <see cref="ValueTask{TResult}"/> per rental and consume it exactly once. The
/// producer must not access this source after calling <see cref="SetResult"/> or
/// <see cref="SetException"/>.
/// </remarks>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class PooledValueTaskSource<T> : IValueTaskSource<T>
{
    private readonly ValueTaskSourcePool<T> _owner;
    private ManualResetValueTaskSourceCore<T> _core;
    private int _isConsumed;

    internal PooledValueTaskSource(
        ValueTaskSourcePool<T> owner,
        bool runContinuationsAsynchronously)
    {
        _owner = owner;
        _core.RunContinuationsAsynchronously = runContinuationsAsynchronously;
    }

    /// <summary>Gets the token for the current rental.</summary>
    public short Version => _core.Version;

    /// <summary>Creates the single value task for the current rental.</summary>
    public ValueTask<T> CreateValueTask() => new(this, Version);

    /// <summary>Completes the current operation successfully.</summary>
    public void SetResult(T result) => _core.SetResult(result);

    /// <summary>Completes the current operation with an error.</summary>
    public void SetException(Exception error)
    {
        ArgumentNullException.ThrowIfNull(error);
        _core.SetException(error);
    }

    T IValueTaskSource<T>.GetResult(short token)
    {
        ValueTaskSourceStatus status = _core.GetStatus(token);
        if (status == ValueTaskSourceStatus.Pending)
        {
            return ThrowNotCompleted();
        }

        if (Interlocked.CompareExchange(ref _isConsumed, 1, 0) != 0)
        {
            return ThrowAlreadyConsumed();
        }

        try
        {
            return _core.GetResult(token);
        }
        finally
        {
            _core.Reset();
            Volatile.Write(ref _isConsumed, 0);
            _owner.Return(this);
        }
    }

    ValueTaskSourceStatus IValueTaskSource<T>.GetStatus(short token) => _core.GetStatus(token);

    void IValueTaskSource<T>.OnCompleted(
        Action<object?> continuation,
        object? state,
        short token,
        ValueTaskSourceOnCompletedFlags flags)
        => _core.OnCompleted(continuation, state, token, flags);

    [DoesNotReturn]
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T ThrowNotCompleted()
        => throw new InvalidOperationException("The operation has not yet completed.");

    [DoesNotReturn]
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T ThrowAlreadyConsumed()
        => throw new InvalidOperationException("The operation has already been consumed.");
}
