// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Provides pools of reusable <see cref="Queue{T}"/> instances.</summary>
/// <typeparam name="T">The element type.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class QueuePool<T>
{
    private readonly ObjectPool<Queue<T>, Policy> _pool;

    /// <summary>Gets the default largest queue capacity retained by a pool.</summary>
    public const int DefaultMaximumRetainedCapacity = 1024;

    /// <summary>Gets the shared pool.</summary>
    public static QueuePool<T> Shared { get; } = new();

    /// <summary>
    /// Gets an opt-in pool that retains one queue per participating thread before using
    /// <see cref="Shared"/> as a bounded fallback.
    /// </summary>
    public static ThreadLocalPool ThreadLocalShared { get; } = new();

    /// <summary>Initializes a pool with default limits.</summary>
    public QueuePool()
        : this(DefaultMaximumRetainedCapacity, ObjectPool<Queue<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom maximum retained queue capacity.</summary>
    public QueuePool(int maxRetainedCapacity)
        : this(maxRetainedCapacity, ObjectPool<Queue<T>, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with custom item and queue capacity limits.</summary>
    public QueuePool(int maxRetainedCapacity, int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegative(maxRetainedCapacity);
#else
        if (maxRetainedCapacity < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(maxRetainedCapacity),
                maxRetainedCapacity,
                null);
        }
#endif
        MaximumRetainedCapacity = maxRetainedCapacity;
        _pool = new ObjectPool<Queue<T>, Policy>(new Policy(maxRetainedCapacity), maxCapacity);
    }

    /// <summary>Gets the maximum number of queues retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets the largest queue capacity retained by this pool.</summary>
    public int MaximumRetainedCapacity { get; }

    /// <summary>Rents an empty queue.</summary>
    public Queue<T> Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Returns a queue, clearing it when retained and discarding it when too large.</summary>
    public void Return(Queue<T> queue)
    {
        ThrowIfNull(queue);

        if (!TryReset(queue))
        {
            return;
        }

        _pool.ReturnWithoutReset(queue);
    }

    private bool TryReset(Queue<T> queue)
    {
        if (Policy.Reset(queue, MaximumRetainedCapacity))
        {
            return true;
        }

        _pool.Destroy(queue);
        return false;
    }

    private static void ThrowIfNull(Queue<T>? queue)
    {
        if (queue is null)
        {
            throw new ArgumentNullException("obj");
        }
    }

    private readonly struct Policy(int maxRetainedCapacity) : IPooledObjectPolicy<Queue<T>>
    {
#if NETSTANDARD2_0
        private static readonly Func<Queue<T>, int, int>? s_ensureCapacity
            = RuntimeCompatibility.CreateEnsureCapacity<Queue<T>>();
#endif

        public Queue<T> Create() => [];

        internal static bool Reset(Queue<T> obj, int maximumRetainedCapacity)
        {
#if NETSTANDARD2_0
            if (s_ensureCapacity is null)
            {
                obj.Clear();
                obj.TrimExcess();
                return true;
            }

            if (s_ensureCapacity(obj, 0) > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
#else
            if (obj.EnsureCapacity(0) > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
#endif
        }

        public bool TryReset(Queue<T> obj) => Reset(obj, maxRetainedCapacity);
    }

    /// <summary>Provides thread-local-first access to <see cref="Shared"/>.</summary>
    public sealed class ThreadLocalPool
    {
        internal ThreadLocalPool()
        {
        }

        /// <summary>Rents an empty queue from the current thread or shared fallback.</summary>
        public Queue<T> Rent()
            => ThreadLocalFrontTier<Queue<T>, Policy>.Rent(Shared._pool);

        /// <summary>Returns a queue to the current thread or shared fallback.</summary>
        public void Return(Queue<T> queue)
        {
            ThrowIfNull(queue);
            if (!Shared.TryReset(queue))
            {
                return;
            }

            if (!ThreadLocalFrontTier<Queue<T>, Policy>.TryReturn(queue))
            {
                Shared._pool.ReturnWithoutReset(queue);
            }
        }
    }
}
