// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Creates and resets poolable objects through <see cref="IResettable"/>.</summary>
/// <typeparam name="T">The resettable reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
readonly struct ResettablePooledObjectPolicy<T> : IPooledObjectPolicy<T>
    where T : class, IResettable, new()
{
    /// <inheritdoc />
    public T Create() => new();

    /// <inheritdoc />
    public bool TryReset(T obj) => obj.TryReset();

    /// <summary>Disposes a discarded object when it implements <see cref="IDisposable"/>.</summary>
    /// <remarks>
    /// Mirrors the interface default behavior; an explicit implementation keeps the constrained
    /// Destroy call devirtualized instead of boxing this struct on every discarded object.
    /// </remarks>
    public void Destroy(T obj)
    {
        if (obj is IDisposable disposable)
        {
            disposable.Dispose();
        }
    }
}
