// <auto-generated/>
#nullable enable

#if !NET6_0_OR_GREATER
using System;
using System.Reflection;

namespace Reservoir;

internal static class RuntimeCompatibility
{
    internal static Func<TCollection, int, int>? CreateEnsureCapacity<TCollection>()
        where TCollection : class
    {
        MethodInfo? method = typeof(TCollection).GetMethod(
            "EnsureCapacity",
            [typeof(int)]);

        return method is null
            ? null
            : (Func<TCollection, int, int>)Delegate.CreateDelegate(
                typeof(Func<TCollection, int, int>),
                method);
    }

    internal static Func<T, bool>? CreateParameterlessBooleanMethod<T>(string name)
        where T : class
    {
        MethodInfo? method = typeof(T).GetMethod(name, Type.EmptyTypes);

        return method is null
            ? null
            : (Func<T, bool>)Delegate.CreateDelegate(typeof(Func<T, bool>), method);
    }
}
#endif
