// <auto-generated/>
#nullable enable

#if !NET10_0_OR_GREATER
using System;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace Reservoir;

internal static class RuntimeCompatibility
{
    internal delegate bool ConditionalWeakTableRemove<TKey, TValue>(
        ConditionalWeakTable<TKey, TValue> table,
        TKey key,
        out TValue value)
        where TKey : class
        where TValue : class;

#if !NET6_0_OR_GREATER
    internal static Func<TCollection, int, int>? CreateEnsureCapacity<TCollection>()
        where TCollection : class
    {
        MethodInfo? method = typeof(TCollection).GetMethod(
            "EnsureCapacity",
            [typeof(int)]);

        return method is null
            ? null
            : (Func<TCollection, int, int>)Delegate.CreateDelegate(
                typeof(Func<TCollection, int, int>),
                method);
    }

    internal static Func<T, bool>? CreateParameterlessBooleanMethod<T>(string name)
        where T : class
    {
        MethodInfo? method = typeof(T).GetMethod(name, Type.EmptyTypes);

        return method is null
            ? null
            : (Func<T, bool>)Delegate.CreateDelegate(typeof(Func<T, bool>), method);
    }

#endif

    internal static ConditionalWeakTableRemove<TKey, TValue>?
        CreateConditionalWeakTableRemove<TKey, TValue>()
        where TKey : class
        where TValue : class
    {
        MethodInfo? method = typeof(ConditionalWeakTable<TKey, TValue>).GetMethod(
            "Remove",
            [typeof(TKey), typeof(TValue).MakeByRefType()]);

        return method is null
            ? null
            : (ConditionalWeakTableRemove<TKey, TValue>)Delegate.CreateDelegate(
                typeof(ConditionalWeakTableRemove<TKey, TValue>),
                method);
    }
}
#endif
