// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal ref struct ScopedPoolLease<T>
    where T : class
{
    private readonly ScopedPoolLeaseState? _state;
    private readonly T? _value;
    private readonly long _token;

    internal ScopedPoolLease(T value)
    {
        _state = ScopedPoolLeaseStateCache<T>.Acquire(out _token);
        _value = value;
    }

    internal ScopedPoolLease(T value, ScopedPoolLeaseState primary)
    {
        ScopedPoolLeaseState state = primary;
        if (!state.TryAcquire(out long token))
        {
            state = ScopedPoolLeaseStateCache.FindAvailable(primary);
            token = state.AcquireAvailable();
        }

        _token = token;
        _state = state;
        _value = value;
    }

    internal readonly T Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            ScopedPoolLeaseState? state = _state;
            if (state is null)
            {
                PooledLeaseThrowHelper.ThrowDisposed();
            }

            state!.ValidateOwnership(_token);
            return _value!;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRelease(out T value)
    {
        ScopedPoolLeaseState? state = _state;
        if (state is not null && state.TryRelease(_token))
        {
            value = _value!;
            return true;
        }

        value = null!;
        return false;
    }
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class ScopedPoolLeaseStateCache<T>
    where T : class
{
    [ThreadStatic]
    private static ScopedPoolLeaseState? _state;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static ScopedPoolLeaseState Acquire(out long token)
    {
        ScopedPoolLeaseState state = _state ?? Initialize();
        if (!state.TryAcquire(out token))
        {
            state = ScopedPoolLeaseStateCache.FindAvailable(state);
            token = state.AcquireAvailable();
        }

        return state;
    }

    // Keep allocation and thread-static publication outside the inlined primary path.
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ScopedPoolLeaseState Initialize()
    {
        var state = new PaddedScopedPoolLeaseState();
        _state = state;
        return state;
    }

}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class ScopedPoolLeaseStateCache
{
    // Keep the caller's ownership token out of this helper so the JIT can promote lease
    // fields to registers even when the deeper lookup cannot be inlined.
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static ScopedPoolLeaseState FindAvailable(ScopedPoolLeaseState primary)
    {
        primary.Next ??= new PaddedScopedPoolLeaseState();
        ScopedPoolLeaseState secondary = primary.Next;
        return secondary.IsAvailable ? secondary : FindAvailableNested(secondary);
    }

    // Deeper rentals rotate through a ring so a warmed recursive traversal does not
    // rescan its active prefix at every depth. Release only advances the ownership version;
    // arbitrary disposal order remains valid.
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static ScopedPoolLeaseState FindAvailableNested(ScopedPoolLeaseState secondary)
    {
        // The secondary state anchors the ring cursor without another thread-static lookup.
        ScopedPoolLeaseState? start = secondary.Next;
        if (start is not null)
        {
            ScopedPoolLeaseState current = start;
            do
            {
                if (current.IsAvailable)
                {
                    secondary.Next = current.Next;
                    return current;
                }

                current = current.Next!;
            }
            while (!ReferenceEquals(current, start));
        }

        var created = new PaddedScopedPoolLeaseState();
        if (start is null)
        {
            created.Next = created;
        }
        else
        {
            created.Next = start.Next;
            start.Next = created;
        }

        secondary.Next = created.Next;
        return created;
    }
}

// The version is written by its owning thread on every scoped rent and release, so the state
// object keeps its own cache lines through the base-class leading pad and the allocated
// subclass's trailing pad; see CacheLinePadded.
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal class ScopedPoolLeaseState : CacheLinePadded
{
    private long _version;

    internal ScopedPoolLeaseState? Next { get; set; }

    internal bool IsAvailable => (_version & 1) == 0;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryAcquire(out long token)
    {
        long version = _version;
        if ((version & 1) != 0)
        {
            token = 0;
            return false;
        }

        token = version + 1;
        _version = token;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal long AcquireAvailable()
    {
        // Selection and acquisition run synchronously on the owning thread.
        Debug.Assert(IsAvailable);
        long token = _version + 1;
        _version = token;
        return token;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ValidateOwnership(long token)
    {
        if (_version != token)
        {
            PooledLeaseThrowHelper.ThrowDisposed();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRelease(long token)
    {
        if (_version != token)
        {
            return false;
        }

        _version = token + 1;
        return true;
    }
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class PaddedScopedPoolLeaseState : ScopedPoolLeaseState
{
#pragma warning disable CS0169 // The field is only there to occupy space.
    private readonly CacheLinePad _trailingPad;
#pragma warning restore CS0169
}
