// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

internal interface IScopedPool<T>
    where T : class
{
    void ReturnScoped(T value);
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal ref struct ScopedPoolLease<T, TPool>
    where T : class
    where TPool : class, IScopedPool<T>
{
    private readonly ScopedPoolLeaseState? _state;
    private readonly TPool? _pool;
    private readonly T? _value;
    private readonly long _token;

    internal ScopedPoolLease(TPool pool, T value)
    {
        _state = ScopedPoolLeaseStateCache<T>.Acquire(out _token);
        _pool = pool;
        _value = value;
    }

    internal readonly T Value
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get
        {
            ScopedPoolLeaseState? state = _state;
            if (state is null)
            {
                PooledLeaseThrowHelper.ThrowDisposed();
            }

            state!.ValidateOwnership(_token);
            return _value!;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void Dispose()
    {
        ScopedPoolLeaseState? state = _state;
        if (state is not null && state.TryRelease(_token))
        {
            _pool!.ReturnScoped(_value!);
        }
    }
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal static class ScopedPoolLeaseStateCache<T>
    where T : class
{
    [ThreadStatic]
    private static ScopedPoolLeaseState? _state;

    internal static ScopedPoolLeaseState Acquire(out long token)
    {
        ScopedPoolLeaseState? state = _state;
        if (state is null)
        {
            state = new ScopedPoolLeaseState();
            _state = state;
        }
        else
        {
            while (!state.TryAcquire(out token))
            {
                state.Next ??= new ScopedPoolLeaseState();
                state = state.Next;
            }

            return state;
        }

        _ = state.TryAcquire(out token);
        return state;
    }
}

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class ScopedPoolLeaseState
{
    private long _version;

    internal ScopedPoolLeaseState? Next { get; set; }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryAcquire(out long token)
    {
        if ((_version & 1) != 0)
        {
            token = 0;
            return false;
        }

        token = _version + 1;
        _version = token;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal void ValidateOwnership(long token)
    {
        if (_version != token)
        {
            PooledLeaseThrowHelper.ThrowDisposed();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRelease(long token)
    {
        if (_version != token)
        {
            return false;
        }

        _version = token + 1;
        return true;
    }
}
