// <auto-generated/>
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Owns an object and returns it only to the pool's bounded shared store on disposal.</summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct SharedPooledLease<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    private readonly ObjectPool<T, TPolicy>? _pool;
    private ScopedPoolLease<T> _lease;

    internal SharedPooledLease(ObjectPool<T, TPolicy> pool, T value)
    {
        _pool = pool;
        _lease = new ScopedPoolLease<T>(value);
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value => _lease.Value;

    /// <summary>Returns the object once; stale or repeated lease copies cannot return it again.</summary>
    public void Dispose()
    {
        if (_lease.TryRelease(out T value))
        {
            _pool!.ReturnSharedValue(value);
        }
    }
}

/// <summary>Owns an object and returns it only to the pool's bounded shared store on disposal.</summary>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
ref struct SharedPooledLease<T>
    where T : class
{
    private readonly ObjectPool<T, ObjectPool<T>.PolicyAdapter>? _pool;
    private ScopedPoolLease<T> _lease;

    internal SharedPooledLease(ObjectPool<T, ObjectPool<T>.PolicyAdapter> pool, T value)
    {
        _pool = pool;
        _lease = new ScopedPoolLease<T>(value);
    }

    /// <summary>Gets the rented object while this lease owns it.</summary>
    public readonly T Value => _lease.Value;

    /// <summary>Returns the object once; stale or repeated lease copies cannot return it again.</summary>
    public void Dispose()
    {
        if (_lease.TryRelease(out T value))
        {
            _pool!.ReturnSharedValue(value);
        }
    }
}
