// <auto-generated/>
#nullable enable

using System;

namespace Reservoir;

/// <summary>Per-thread slow-scan cursors shared by every small object pool.</summary>
/// <remarks>
/// A thread static on the generic pool is reached through a generic-lookup helper call in shared
/// generic code (every reference-type pool), so the cursors live on this non-generic type, whose
/// thread statics use a cheaper access path. They are only scan-order hints: pools of different
/// types and sizes sharing them can make a scan start elsewhere, but never skip a slot.
/// </remarks>
internal static class SmallPoolScanCursor
{
    // Physical slot index of this thread's last slow-path rent hit.
    [ThreadStatic]
    internal static int Rent;

    // Physical slot index of this thread's last slow-path return placement.
    [ThreadStatic]
    internal static int Return;
}
