// <auto-generated/>
#nullable enable

using System;

namespace Reservoir;

/// <summary>Per-thread scan cursor shared by every small object pool.</summary>
/// <remarks>
/// A thread static on the generic pool would be reached through a runtime helper call in shared
/// generic code (every reference-type pool), so the cursor lives on this non-generic type, whose
/// thread static the JIT accesses inline. It is only a scan-order hint, so pools of different
/// types and sizes sharing it can make a scan start elsewhere but never skip a slot.
/// </remarks>
internal static class SmallPoolScanCursor
{
    [ThreadStatic]
    internal static int Value;
}
