// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Threading;

namespace Reservoir;

/// <summary>Dense bounded storage for large pools, striped to spread atomic contention.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class StripedObjectStore<T>
    where T : class
{
    private const int MaximumStripeCount = 32;
    private const int MinimumSlotsPerStripe = 8;

    [ThreadStatic]
    private static int _threadStripe;

    // One-based index of the last successful remote stripe. Only cache affinity, never items or
    // store references; another store of the same T can reuse this hint with a different size.
    [ThreadStatic]
    private static int _lastRentStripe;

    private static int s_nextThreadStripe;

    private readonly Stripe[] _stripes;
    private readonly int _stripeMask;
    private readonly ulong _stripeModulusMultiplier;

    internal StripedObjectStore(int capacity)
        : this(capacity, Environment.ProcessorCount)
    {
    }

    internal StripedObjectStore(int capacity, int processorLimit)
    {
        int stripeCount = GetStripeCount(capacity, processorLimit);
        _stripeMask = (stripeCount & (stripeCount - 1)) == 0 ? stripeCount - 1 : -1;
        _stripeModulusMultiplier = ulong.MaxValue / (uint)stripeCount + 1;
        _stripes = new Stripe[stripeCount];

        int baseCapacity = capacity / stripeCount;
        int extraSlots = capacity % stripeCount;

        for (int i = 0; i < stripeCount; i++)
        {
            _stripes[i] = new PaddedStripe(baseCapacity + (i < extraSlots ? 1 : 0));
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryPop(out T? item)
    {
        int start = GetStartStripe();
        if (TryPopAt(start, out item))
        {
            return true;
        }

        return TryPopSlow(start, out item);
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private bool TryPopSlow(int start, out T? item)
    {
        // A completion thread often returns to the same remote stripe repeatedly. Try that
        // location before scanning, while keeping same-thread reuse on the home stripe.
        int hint = _lastRentStripe - 1;
        if ((uint)hint < (uint)_stripes.Length && hint != start && TryPopAt(hint, out item))
        {
            return true;
        }

        int index = start;
        for (int i = 1; i < _stripes.Length; i++)
        {
            if (++index == _stripes.Length)
            {
                index = 0;
            }

            if (TryPopAt(index, out item))
            {
                _lastRentStripe = index + 1;
                return true;
            }
        }

        item = null;
        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private bool TryPopAt(int index, out T? item)
    {
        Stripe stripe = _stripes[index];
        T? observed = Volatile.Read(ref stripe.FastItem);
        if (observed is not null
            && ReferenceEquals(Interlocked.CompareExchange(ref stripe.FastItem, null, observed), observed))
        {
            item = observed;
            return true;
        }

        return TryPop(stripe, out item);
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryPush(T item)
    {
        int stripeIndex = GetStartStripe();

        for (int i = 0; i < _stripes.Length; i++)
        {
            Stripe stripe = _stripes[stripeIndex];
            // Test before the exchange so an occupied direct slot costs a shared read instead of
            // a failed locked operation that steals the line from the stripe's other users.
            if ((Volatile.Read(ref stripe.FastItem) is null
                    && Interlocked.CompareExchange(ref stripe.FastItem, item, null) is null)
                || TryPush(stripe, item))
            {
                return true;
            }

            if (++stripeIndex == _stripes.Length)
            {
                stripeIndex = 0;
            }
        }

        return false;
    }

    // Each stripe is a bounded MPMC ring (Vyukov): a per-cell sequence number tells a claimant
    // whether the cell is ready, so a pop or push owns its cell after a single head or tail CAS.
    private static bool TryPop(Stripe stripe, out T? item)
    {
        Cell[] cells = stripe.Cells;
        long position = Volatile.Read(ref stripe.Head);
        SpinWait spinner = default;
        while (true)
        {
            ref Cell cell = ref cells[(int)position & stripe.Mask];
            long difference = Volatile.Read(ref cell.Sequence) - (position + 1);
            if (difference == 0)
            {
                long observed = Interlocked.CompareExchange(ref stripe.Head, position + 1, position);
                if (observed == position)
                {
                    // Winning the head CAS owns this cell until its sequence is republished.
                    item = cell.Item;
                    cell.Item = null;
                    Volatile.Write(ref cell.Sequence, position + cells.Length);
                    return item is not null;
                }

                position = observed;
            }
            else if (difference < 0)
            {
                if (Volatile.Read(ref stripe.Tail) == position)
                {
                    item = null;
                    return false;
                }

                // A pusher claimed this cell and is publishing it: the stripe is not empty.
                spinner.SpinOnce();
                position = Volatile.Read(ref stripe.Head);
            }
            else
            {
                position = Volatile.Read(ref stripe.Head);
            }
        }
    }

    private static bool TryPush(Stripe stripe, T item)
    {
        Cell[] cells = stripe.Cells;
        long position = Volatile.Read(ref stripe.Tail);
        SpinWait spinner = default;
        while (true)
        {
            // The ring rounds up to a power of two; the head read after the tail can only
            // overstate occupancy, so the exact capacity is never exceeded.
            if (position - Volatile.Read(ref stripe.Head) >= stripe.Capacity)
            {
                return false;
            }

            ref Cell cell = ref cells[(int)position & stripe.Mask];
            long difference = Volatile.Read(ref cell.Sequence) - position;
            if (difference == 0)
            {
                long observed = Interlocked.CompareExchange(ref stripe.Tail, position + 1, position);
                if (observed == position)
                {
                    cell.Item = item;
                    Volatile.Write(ref cell.Sequence, position + 1);
                    return true;
                }

                position = observed;
            }
            else if (difference < 0)
            {
                // The capacity check found room, so a popper claimed this cell and is releasing
                // it. Wait rather than reject an item the pool has room for.
                spinner.SpinOnce();
                position = Volatile.Read(ref stripe.Tail);
            }
            else
            {
                position = Volatile.Read(ref stripe.Tail);
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetStartStripe()
    {
        int threadStripe = _threadStripe;
        if (threadStripe == 0)
        {
            do
            {
                threadStripe = Interlocked.Increment(ref s_nextThreadStripe);
            }
            while (threadStripe == 0);

            _threadStripe = threadStripe;
        }

        return GetAffinityIndex(unchecked((uint)(threadStripe - 1)));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal int GetAffinityIndex(uint threadOrdinal)
    {
        if (_stripeMask >= 0)
        {
            return (int)(threadOrdinal & (uint)_stripeMask);
        }

        uint stripeCount = (uint)_stripes.Length;
        if (IntPtr.Size == 8)
        {
            return (int)FastMod(threadOrdinal, stripeCount, _stripeModulusMultiplier);
        }

        return (int)(threadOrdinal % stripeCount);
    }

    internal static int GetStripeCount(int capacity, int processorLimit)
    {
        int capacityLimit = Math.Max(1, capacity / MinimumSlotsPerStripe);
        int processorCount = Math.Min(processorLimit, MaximumStripeCount);
        return Math.Max(1, Math.Min(processorCount, capacityLimit));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint FastMod(uint value, uint divisor, ulong multiplier)
        => (uint)(((((multiplier * value) >> 32) + 1) * divisor) >> 32);

    // A stripe is the unit of contention, so its hot fields get their own cache lines through the
    // base-class leading pad and the allocated subclass's trailing pad; see CacheLinePadded.
    private class Stripe : CacheLinePadded
    {
        internal readonly Cell[] Cells;
        internal readonly int Mask;
        internal readonly int Capacity;
        internal long Head;
        internal long Tail;
        internal T? FastItem;

        internal Stripe(int capacity)
        {
            // The directly exchanged item replaces one ring cell in the exact capacity.
            Capacity = capacity - 1;
            int length = 1;
            while (length < Capacity)
            {
                length <<= 1;
            }

            Cells = new Cell[length];
            Mask = length - 1;
            for (int i = 0; i < Cells.Length; i++)
            {
                Cells[i].Sequence = i;
            }
        }
    }

    private sealed class PaddedStripe : Stripe
    {
#pragma warning disable CS0169 // The field is only there to occupy space.
        private readonly CacheLinePad _trailingPad;
#pragma warning restore CS0169

        internal PaddedStripe(int capacity)
            : base(capacity)
        {
        }
    }

    private struct Cell
    {
        internal T? Item;
        internal long Sequence;
    }
}
