// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;

namespace Reservoir;

/// <summary>Dense bounded storage for large pools, striped to spread atomic contention.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal sealed class StripedObjectStore<T>
    where T : class
{
    private const int EmptyIndex = -1;
    private const int MaximumStripeCount = 32;
    private const int MinimumSlotsPerStripe = 16;

    [ThreadStatic]
    private static int _threadStripe;

    private static int s_nextThreadStripe;

    private readonly Stripe[] _stripes;
    private readonly int _stripeMask;
    private readonly ulong _stripeModulusMultiplier;

    internal StripedObjectStore(int capacity)
        : this(capacity, Environment.ProcessorCount)
    {
    }

    internal StripedObjectStore(int capacity, int processorLimit)
    {
        int stripeCount = GetStripeCount(capacity, processorLimit);
        _stripeMask = (stripeCount & (stripeCount - 1)) == 0 ? stripeCount - 1 : -1;
        _stripeModulusMultiplier = ulong.MaxValue / (uint)stripeCount + 1;
        _stripes = new Stripe[stripeCount];

        int baseCapacity = capacity / stripeCount;
        int extraSlots = capacity % stripeCount;

        for (int i = 0; i < stripeCount; i++)
        {
            _stripes[i] = new Stripe(baseCapacity + (i < extraSlots ? 1 : 0));
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryPop(out T? item)
    {
        int stripeIndex = GetStartStripe();

        for (int i = 0; i < _stripes.Length; i++)
        {
            if (TryPop(_stripes[stripeIndex], out item))
            {
                return true;
            }

            if (++stripeIndex == _stripes.Length)
            {
                stripeIndex = 0;
            }
        }

        item = null;
        return false;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryPush(T item)
    {
        int stripeIndex = GetStartStripe();

        for (int i = 0; i < _stripes.Length; i++)
        {
            if (TryPush(_stripes[stripeIndex], item))
            {
                return true;
            }

            if (++stripeIndex == _stripes.Length)
            {
                stripeIndex = 0;
            }
        }

        return false;
    }

    private static bool TryPop(Stripe stripe, out T? item)
    {
        if (!TryTakeNode(ref stripe.AvailableHead, stripe.Nodes, out int nodeIndex))
        {
            item = null;
            return false;
        }

        // Winning the available-head CAS owns this node until free-head publication.
        item = stripe.Nodes[nodeIndex].Item;
        stripe.Nodes[nodeIndex].Item = null;
        PublishNode(ref stripe.FreeHead, stripe.Nodes, nodeIndex);
        return item is not null;
    }

    private static bool TryPush(Stripe stripe, T item)
    {
        if (!TryTakeNode(ref stripe.FreeHead, stripe.Nodes, out int nodeIndex))
        {
            return false;
        }

        Volatile.Write(ref stripe.Nodes[nodeIndex].Item, item);
        PublishNode(ref stripe.AvailableHead, stripe.Nodes, nodeIndex);
        return true;
    }

    private static bool TryTakeNode(ref long head, Node[] nodes, out int nodeIndex)
    {
        while (true)
        {
            long observedHead = Volatile.Read(ref head);
            nodeIndex = GetIndex(observedHead);
            if (nodeIndex == EmptyIndex)
            {
                return false;
            }

            int nextIndex = Volatile.Read(ref nodes[nodeIndex].Next);
            long updatedHead = NextHead(observedHead, nextIndex);
            if (Interlocked.CompareExchange(ref head, updatedHead, observedHead) == observedHead)
            {
                return true;
            }
        }
    }

    private static void PublishNode(ref long head, Node[] nodes, int nodeIndex)
    {
        while (true)
        {
            long observedHead = Volatile.Read(ref head);
            Volatile.Write(ref nodes[nodeIndex].Next, GetIndex(observedHead));
            long updatedHead = NextHead(observedHead, nodeIndex);
            if (Interlocked.CompareExchange(ref head, updatedHead, observedHead) == observedHead)
            {
                return;
            }
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private int GetStartStripe()
    {
        int threadStripe = _threadStripe;
        if (threadStripe == 0)
        {
            do
            {
                threadStripe = Interlocked.Increment(ref s_nextThreadStripe);
            }
            while (threadStripe == 0);

            _threadStripe = threadStripe;
        }

        return GetAffinityIndex(unchecked((uint)(threadStripe - 1)));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal int GetAffinityIndex(uint threadOrdinal)
    {
        if (_stripeMask >= 0)
        {
            return (int)(threadOrdinal & (uint)_stripeMask);
        }

        uint stripeCount = (uint)_stripes.Length;
        if (IntPtr.Size == 8)
        {
            return (int)FastMod(threadOrdinal, stripeCount, _stripeModulusMultiplier);
        }

        return (int)(threadOrdinal % stripeCount);
    }

    internal static int GetStripeCount(int capacity, int processorLimit)
    {
        int capacityLimit = Math.Max(1, capacity / MinimumSlotsPerStripe);
        int processorCount = Math.Min(processorLimit, MaximumStripeCount);
        return Math.Max(1, Math.Min(processorCount, capacityLimit));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static uint FastMod(uint value, uint divisor, ulong multiplier)
        => (uint)(((((multiplier * value) >> 32) + 1) * divisor) >> 32);

    private static long PackHead(int version, int index)
        => ((long)version << 32) | (uint)index;

    private static long NextHead(long observedHead, int index)
        => PackHead(unchecked((int)(observedHead >> 32) + 1), index);

    private static int GetIndex(long head) => (int)head;

    [StructLayout(LayoutKind.Sequential, Size = 128)]
    private sealed class Stripe
    {
        internal readonly Node[] Nodes;
        internal long AvailableHead;
        internal long FreeHead;

        internal Stripe(int capacity)
        {
            Nodes = new Node[capacity];

            for (int i = 0; i < capacity; i++)
            {
                Nodes[i].Next = i + 1 < capacity ? i + 1 : EmptyIndex;
            }

            AvailableHead = PackHead(0, EmptyIndex);
            FreeHead = PackHead(0, 0);
        }
    }

    private struct Node
    {
        internal T? Item;
        internal int Next;
    }
}
