// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace Reservoir;

/// <summary>Provides pools of reusable <see cref="StringBuilder"/> instances.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public
sealed class StringBuilderPool : IScopedPool<StringBuilder>
{
    private readonly ObjectPool<StringBuilder, Policy> _pool;
    private InstanceThreadLocalFrontTier<StringBuilder> _scopedTier;

    /// <summary>Gets the default largest builder capacity retained by a pool.</summary>
    public const int DefaultMaximumRetainedCapacity = 4096;

    /// <summary>Gets the shared pool.</summary>
    public static StringBuilderPool Shared { get; } = new();

    /// <summary>
    /// Gets an opt-in pool that retains one builder per participating thread before using
    /// <see cref="Shared"/> as a bounded fallback.
    /// </summary>
    public static ThreadLocalPool ThreadLocalShared { get; } = new();

    /// <summary>Initializes a pool with default limits.</summary>
    public StringBuilderPool()
        : this(
            DefaultMaximumRetainedCapacity,
            ObjectPool<StringBuilder, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with a custom maximum retained builder capacity.</summary>
    public StringBuilderPool(int maxRetainedCapacity)
        : this(maxRetainedCapacity, ObjectPool<StringBuilder, Policy>.DefaultMaximumRetained)
    {
    }

    /// <summary>Initializes a pool with custom item and builder capacity limits.</summary>
    public StringBuilderPool(int maxRetainedCapacity, int maxCapacity)
    {
#if NET8_0_OR_GREATER
        ArgumentOutOfRangeException.ThrowIfNegative(maxRetainedCapacity);
#else
        if (maxRetainedCapacity < 0)
        {
            throw new ArgumentOutOfRangeException(
                nameof(maxRetainedCapacity),
                maxRetainedCapacity,
                null);
        }
#endif
        MaximumRetainedCapacity = maxRetainedCapacity;
        _pool = new ObjectPool<StringBuilder, Policy>(new Policy(maxRetainedCapacity), maxCapacity);
    }

    /// <summary>Gets the maximum number of builders retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets the largest builder capacity retained by this pool.</summary>
    public int MaximumRetainedCapacity { get; }

    /// <summary>Rents an empty string builder.</summary>
    public StringBuilder Rent() => _pool.RentWithoutLifecycle();

    /// <summary>Rents an empty builder owned by a stack-only thread-local lease.</summary>
    public Lease RentScoped()
        => new(this, _scopedTier.Rent(_pool));

    /// <summary>
    /// Rents an empty builder owned by a stack-only thread-local lease and exposes it directly.
    /// </summary>
    public Lease RentScoped(out StringBuilder builder)
    {
        builder = _scopedTier.Rent(_pool);
        return new Lease(this, builder);
    }

    /// <summary>Returns a builder, clearing it when retained and discarding it when incompatible or too large.</summary>
    public void Return(StringBuilder builder)
    {
        ThrowIfNull(builder);

        if (!TryReset(builder))
        {
            return;
        }

        _pool.ReturnWithoutReset(builder);
    }

    private bool TryReset(StringBuilder builder)
    {
        if (Policy.Reset(builder, MaximumRetainedCapacity))
        {
            return true;
        }

        _pool.Destroy(builder);
        return false;
    }

    void IScopedPool<StringBuilder>.ReturnScoped(StringBuilder builder)
    {
        if (!TryReset(builder))
        {
            return;
        }

        if (!_scopedTier.TryReturn(builder))
        {
            _pool.ReturnWithoutReset(builder);
        }
    }

    private static void ThrowIfNull(StringBuilder? builder)
    {
        if (builder is null)
        {
            throw new ArgumentNullException("obj");
        }
    }

    private readonly struct Policy(int maxRetainedCapacity) : IPooledObjectPolicy<StringBuilder>
    {
        public StringBuilder Create() => new();

        internal static bool Reset(StringBuilder obj, int maximumRetainedCapacity)
        {
            if (obj.MaxCapacity != int.MaxValue
                || obj.Capacity > maximumRetainedCapacity)
            {
                return false;
            }

            obj.Clear();
            return true;
        }

        public bool TryReset(StringBuilder obj) => Reset(obj, maxRetainedCapacity);
    }

    /// <summary>Owns a thread-local builder rental and returns it when disposed.</summary>
    public ref struct Lease
    {
        private ScopedPoolLease<StringBuilder, StringBuilderPool> _lease;

        internal Lease(StringBuilderPool pool, StringBuilder builder)
        {
            _lease = new ScopedPoolLease<StringBuilder, StringBuilderPool>(pool, builder);
        }

        /// <summary>Gets the rented builder while this lease owns it.</summary>
        public readonly StringBuilder Value => _lease.Value;

        /// <summary>Returns the builder. Repeated calls and stale copies are ignored.</summary>
        public void Dispose() => _lease.Dispose();
    }

    /// <summary>Provides thread-local-first access to <see cref="Shared"/>.</summary>
    public sealed class ThreadLocalPool
    {
        internal ThreadLocalPool()
        {
        }

        /// <summary>Rents an empty builder from the current thread or shared fallback.</summary>
        public StringBuilder Rent()
            => ThreadLocalFrontTier<StringBuilder, Policy>.Rent(Shared._pool);

        /// <summary>Returns a builder to the current thread or shared fallback.</summary>
        public void Return(StringBuilder builder)
        {
            ThrowIfNull(builder);
            if (!Shared.TryReset(builder))
            {
                return;
            }

            if (!ThreadLocalFrontTier<StringBuilder, Policy>.TryReturn(builder))
            {
                Shared._pool.ReturnWithoutReset(builder);
            }
        }
    }
}
