// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
#if NETCOREAPP3_0_OR_GREATER
using System.Runtime.InteropServices;
#endif
using System.Threading;

namespace Reservoir;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal struct TrackedInstanceThreadLocalFrontTier<T>
    where T : class
{
#if NETCOREAPP3_0_OR_GREATER
    // The plain-ops take below is proven only against x86-TSO (in-order retirement plus
    // snoop-triggered replay of early loads); weaker architectures and TFMs without
    // Interlocked.MemoryBarrierProcessWide keep the interlocked take.
    private static readonly bool s_asymmetricClear =
        RuntimeInformation.ProcessArchitecture is Architecture.X86 or Architecture.X64;
#endif

    private ThreadLocal<Slot>? _slots;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T Rent<TPolicy>(ObjectPool<T, TPolicy> fallback)
        where TPolicy : struct, IPooledObjectPolicy<T>
        => Rent(fallback, out _);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T Rent<TPolicy>(ObjectPool<T, TPolicy> fallback, out Slot slot)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        slot = GetSlot();
        // The take must be exclusive against a concurrent Clear or Dispose, which would
        // otherwise destroy the item after a plain read observed it. The cheap read first keeps
        // empty slots off both protected paths.
        T? item;
#if NETCOREAPP3_0_OR_GREATER
        if (s_asymmetricClear)
        {
            // Plain-cost take. The gate is a generation counter: Clear makes it odd before its
            // process-wide barrier and even again only after taking from this slot, so an
            // unchanged even gate across the take proves no Clear boundary was crossed — a take
            // whose null-store retired before the barrier is visible to Clear's exchange, and
            // any later or straddling take observes a changed or odd gate here and reconciles.
            // Volatile keeps the compiler from reordering the gate loads across the item
            // accesses; x86 needs no fence.
            int gate = Volatile.Read(ref slot.Gate);
            item = slot.Item;
            if (item is not null)
            {
                Volatile.Write(ref slot.Item, null);
                if ((Volatile.Read(ref slot.Gate) == gate && (gate & 1) == 0)
                    || (item = ReconcileRacedTake(slot, item!)) is not null)
                {
                    return item;
                }
            }
        }
        else
        {
            item = slot.Item;
            if (item is not null
                && (item = Interlocked.Exchange(ref slot.Item, null)) is not null)
            {
                return item;
            }
        }
#else
        item = slot.Item;
        if (item is not null
            && (item = Interlocked.Exchange(ref slot.Item, null)) is not null)
        {
            return item;
        }
#endif

        // A hit proves a prior return stored here, which the Rents gate already allowed, so
        // the flag only needs to be raised on the miss path; the hit path stays write-free.
        if (!slot.Rents)
        {
            slot.Rents = true;
        }

        return fallback.RentWithoutLifecycle();
    }

#if NETCOREAPP3_0_OR_GREATER
    [MethodImpl(MethodImplOptions.NoInlining)]
    private static T? ReconcileRacedTake(Slot slot, T item)
    {
        // The gate generation changed or was odd, so a Clear may have crossed this thread's
        // plain-stores take of the slot; either side may have captured the item. Clear
        // records every capture under the slot lock before destroying it, and only the owning
        // thread refills the slot, so LastTaken answers deterministically whether the racing
        // Clear captured this item. If Clear is still ahead of its take for this slot, the lock
        // makes it observe our null-store afterwards and capture nothing.
        lock (slot)
        {
            if (slot.LastTaken is { } lastTaken
                && lastTaken.TryGetTarget(out T? captured)
                && ReferenceEquals(captured, item))
            {
                // The renter keeps item alive while reconciling, so a weak record cannot lose
                // this match. Clear the target once this take has acknowledged destruction.
                lastTaken.SetTarget(null!);
                return null;
            }

            return item;
        }
    }
#endif

    // Only threads that rent may park a return in their slot; on a thread that exclusively
    // returns (an IO or completion thread receiving handed-off objects) the parked object would
    // never be rented again, starving the shared tier of it until Clear runs.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryReturn(T item)
    {
        Slot slot = GetSlot();
        if (!slot.Rents)
        {
            return false;
        }

        return TryReturn(slot, item);
    }

    // A lease-carried slot belongs to the returning thread; only Clear races with publication.
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool TryReturn(Slot slot, T item)
    {
        if (slot.Item is not null)
        {
            return false;
        }

#if NETCOREAPP3_0_OR_GREATER
        if (s_asymmetricClear)
        {
            slot.Item = item;
            return true;
        }
#endif

        // Publish before the caller's disposed-state recheck. Without a store/load fence,
        // that recheck can see an open pool while Dispose's exchange misses a buffered store.
        // The asymmetric path gets the corresponding ordering from Clear's process-wide barrier.
        Interlocked.Exchange(ref slot.Item, item);
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRemove(T item) => TryRemove(GetSlot(), item);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static bool TryRemove(Slot slot, T item)
        => ReferenceEquals(
            Interlocked.CompareExchange(ref slot.Item, null, item),
            item);

    internal void Clear<TPolicy>(ObjectPool<T, TPolicy> fallback)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        if (slots is null)
        {
            return;
        }

        Exception? firstException = null;
#if NETCOREAPP3_0_OR_GREATER
        if (s_asymmetricClear)
        {
            // Serializing clears gives every per-slot gate a single writer, and one snapshot for
            // both passes guarantees no slot is taken from without its gate raised first. A slot
            // created after the snapshot is missed, which matches the existing behavior of a
            // return racing Clear.
            T?[] capturedItems;
            lock (slots)
            {
                var snapshot = slots.Values;
                // Reserve the capture buffer before raising gates. Each Clear owns its buffer,
                // so callbacks may reenter Clear or clear another pool after we release locks.
                int count = snapshot.Count;
                capturedItems = new T?[count];
                for (int i = 0; i < count; i++)
                {
                    Slot slot = snapshot[i];
                    // Serialized clears make this the gate's only writer; odd marks in-progress.
                    Volatile.Write(ref slot.Gate, unchecked(slot.Gate + 1));
                }

                // Drain every core: a renter whose take retired before this barrier has its
                // null-store visible to the exchanges below; a later take observes its raised
                // gate and reconciles through the slot lock instead.
                Interlocked.MemoryBarrierProcessWide();

                for (int i = 0; i < count; i++)
                {
                    Slot slot = snapshot[i];
                    T? item;
                    lock (slot)
                    {
                        item = Interlocked.Exchange(ref slot.Item, null);
                        if (item is not null)
                        {
                            if (slot.LastTaken is { } lastTaken)
                            {
                                lastTaken.SetTarget(item);
                            }
                            else
                            {
                                slot.LastTaken = new WeakReference<T>(item);
                            }
                        }

                        // Back to even only after this slot's take, so a renter that straddled
                        // it sees a changed generation and reconciles.
                        Volatile.Write(ref slot.Gate, unchecked(slot.Gate + 1));
                    }

                    capturedItems[i] = item;
                }
            }

            // Gate reconciliation is complete. Never invoke user cleanup while holding either
            // the collection lock or a slot lock: callbacks can wait for other pool operations.
            foreach (T? item in capturedItems)
            {
                if (item is null)
                {
                    continue;
                }

                try
                {
                    fallback.Destroy(item);
                }
                catch (Exception exception)
                {
                    firstException ??= exception;
                }
            }

            if (firstException is not null)
            {
                ExceptionDispatchInfo.Capture(firstException).Throw();
            }

            return;
        }
#endif

        foreach (Slot slot in slots.Values)
        {
            T? item = Interlocked.Exchange(ref slot.Item, null);
            if (item is null)
            {
                continue;
            }

            try
            {
                fallback.Destroy(item);
            }
            catch (Exception exception)
            {
                firstException ??= exception;
            }
        }

        if (firstException is not null)
        {
            ExceptionDispatchInfo.Capture(firstException).Throw();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private Slot GetSlot()
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        return (slots ?? InitializeSlots()).Value!;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private ThreadLocal<Slot> InitializeSlots()
    {
        var created = new ThreadLocal<Slot>(
            static () => new PaddedSlot(),
            trackAllValues: true);
        ThreadLocal<Slot>? existing = Interlocked.CompareExchange(ref _slots, created, null);
        if (existing is null)
        {
            return created;
        }

        created.Dispose();
        return existing;
    }

    // Ownership versions and nested lease states belong to the renting thread. Clear only
    // touches the retained-item fields below, leaving outstanding leases valid. The leading
    // and trailing pads keep each slot on its own cache lines; see CacheLinePadded.
    internal class Slot : ScopedPoolLeaseState
    {
        internal T? Item;
        // True once the owning thread has rented from this pool. Written and read only by the
        // owning thread, so plain accesses are safe; Clear never needs it because it drains
        // Item regardless of who parked it.
        internal bool Rents;
#if NETCOREAPP3_0_OR_GREATER
        // Generation counter written only by (serialized) clears: incremented to odd before the
        // process-wide barrier and back to even under the slot lock after this slot's take. A
        // renter whose take saw a changed or odd generation reconciles instead of trusting it.
        internal int Gate;
        // The item the most recent capturing Clear took from this slot, recorded under the slot
        // lock; lets a raced renter distinguish "Clear captured my item" from "my take won".
        // A destroyed object must be collectible even when no renter raced Clear. A racing
        // renter holds its own strong reference until reconciliation. Allocate the weak handle
        // only on the first capturing Clear, then reuse it for later clears.
        internal WeakReference<T>? LastTaken;
#endif
    }

    private sealed class PaddedSlot : Slot
    {
#pragma warning disable CS0169 // The field is only there to occupy space.
        private readonly CacheLinePad _trailingPad;
#pragma warning restore CS0169
    }
}
