// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;

namespace Reservoir;

[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
internal struct TrackedInstanceThreadLocalFrontTier<T>
    where T : class
{
    private ThreadLocal<Slot>? _slots;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal T Rent<TPolicy>(ObjectPool<T, TPolicy> fallback)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        Slot slot = GetSlot();
        T? item = slot.Item;
        if (item is null)
        {
            return fallback.RentWithoutLifecycle();
        }

        slot.Item = null;
        return item;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryReturn(T item)
    {
        Slot slot = GetSlot();
        if (slot.Item is not null)
        {
            return false;
        }

        slot.Item = item;
        return true;
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal bool TryRemove(T item)
    {
        Slot slot = GetSlot();
        return ReferenceEquals(
            Interlocked.CompareExchange(ref slot.Item, null, item),
            item);
    }

    internal void Clear<TPolicy>(ObjectPool<T, TPolicy> fallback)
        where TPolicy : struct, IPooledObjectPolicy<T>
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        if (slots is null)
        {
            return;
        }

        Exception? firstException = null;
        foreach (Slot slot in slots.Values)
        {
            T? item = Interlocked.Exchange(ref slot.Item, null);
            if (item is null)
            {
                continue;
            }

            try
            {
                fallback.Destroy(item);
            }
            catch (Exception exception)
            {
                firstException ??= exception;
            }
        }

        if (firstException is not null)
        {
            ExceptionDispatchInfo.Capture(firstException).Throw();
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private Slot GetSlot()
    {
        ThreadLocal<Slot>? slots = Volatile.Read(ref _slots);
        return (slots ?? InitializeSlots()).Value!;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private ThreadLocal<Slot> InitializeSlots()
    {
        var created = new ThreadLocal<Slot>(
            static () => new Slot(),
            trackAllValues: true);
        ThreadLocal<Slot>? existing = Interlocked.CompareExchange(ref _slots, created, null);
        if (existing is null)
        {
            return created;
        }

        created.Dispose();
        return existing;
    }

    private sealed class Slot
    {
        internal T? Item;
    }
}
