// <auto-generated/>
#nullable enable

using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;

namespace Reservoir;

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T,TPolicy}"/> without copy-safety checks.
/// </summary>
/// <remarks>
/// This lease must not be copied. Call <see cref="Dispose"/> exactly once across all copies.
/// Violating that contract can return the same object more than once. Use
/// <see cref="PooledLease{T,TPolicy}"/> when copy safety or repeated-dispose safety is required.
/// </remarks>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
/// <typeparam name="TPolicy">The policy used to create, reset, and destroy objects.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public readonly ref struct UncheckedPooledLease<T, TPolicy>
    where T : class
    where TPolicy : struct, IPooledObjectPolicy<T>
{
    private readonly ObjectPool<T, TPolicy> _pool;
    private readonly T _value;

    internal UncheckedPooledLease(ObjectPool<T, TPolicy> pool, T value)
    {
        _pool = pool;
        _value = value;
    }

    /// <summary>Gets the rented object.</summary>
    public T Value => _value;

    /// <summary>Returns the rented object. Must be called exactly once across all copies.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Dispose() => _pool.Return(_value);
}

/// <summary>
/// Owns an object rented from an <see cref="ObjectPool{T}"/> without copy-safety checks.
/// </summary>
/// <remarks>
/// This lease must not be copied. Call <see cref="Dispose"/> exactly once across all copies.
/// Violating that contract can return the same object more than once. Use
/// <see cref="PooledLease{T}"/> when copy safety or repeated-dispose safety is required.
/// </remarks>
/// <typeparam name="T">The reference type stored by the pool.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
public readonly ref struct UncheckedPooledLease<T>
    where T : class
{
    private readonly UncheckedPooledLease<T, ObjectPool<T>.PolicyAdapter> _lease;

    internal UncheckedPooledLease(
        UncheckedPooledLease<T, ObjectPool<T>.PolicyAdapter> lease)
    {
        _lease = lease;
    }

    /// <summary>Gets the rented object.</summary>
    public T Value => _lease.Value;

    /// <summary>Returns the rented object. Must be called exactly once across all copies.</summary>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Dispose() => _lease.Dispose();
}
