// <auto-generated/>
#nullable enable

using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;

namespace Reservoir;

/// <summary>Provides pools of reusable manually completed value task sources.</summary>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class ValueTaskSourcePool : IDisposable
{
    private readonly ObjectPool<PooledValueTaskSource, Policy> _pool;

    /// <summary>Gets the shared pool.</summary>
    public static ValueTaskSourcePool Shared { get; } = new();

    /// <summary>Initializes a pool with the default capacity and inline continuations.</summary>
    public ValueTaskSourcePool()
        : this(
            ObjectPool<PooledValueTaskSource, Policy>.DefaultMaximumRetained,
            runContinuationsAsynchronously: false)
    {
    }

    /// <summary>Initializes a pool with the default capacity and continuation behavior.</summary>
    public ValueTaskSourcePool(bool runContinuationsAsynchronously)
        : this(
            ObjectPool<PooledValueTaskSource, Policy>.DefaultMaximumRetained,
            runContinuationsAsynchronously)
    {
    }

    /// <summary>Initializes a pool with a custom capacity and continuation behavior.</summary>
    public ValueTaskSourcePool(
        int maxCapacity,
        bool runContinuationsAsynchronously = false)
    {
        RunContinuationsAsynchronously = runContinuationsAsynchronously;
        _pool = new ObjectPool<PooledValueTaskSource, Policy>(
            new Policy(this, runContinuationsAsynchronously),
            maxCapacity);
    }

    /// <summary>Gets the maximum number of sources retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets whether continuations are scheduled asynchronously.</summary>
    public bool RunContinuationsAsynchronously { get; }

    /// <summary>Rents a source that returns to this pool when its value task is consumed.</summary>
    public PooledValueTaskSource Rent() => _pool.Rent();

    /// <summary>Removes all retained sources while leaving the pool usable.</summary>
    public void Clear() => _pool.Clear();

    /// <summary>Closes a dedicated pool. Disposing <see cref="Shared"/> only clears it.</summary>
    public void Dispose()
    {
        if (ReferenceEquals(this, Shared))
        {
            _pool.Clear();
            return;
        }

        _pool.Dispose();
    }

    internal void Return(PooledValueTaskSource source) => _pool.Return(source);

    internal readonly struct Policy : IPooledObjectPolicy<PooledValueTaskSource>
    {
        private readonly ValueTaskSourcePool _owner;
        private readonly bool _runContinuationsAsynchronously;

        internal Policy(ValueTaskSourcePool owner, bool runContinuationsAsynchronously)
        {
            _owner = owner;
            _runContinuationsAsynchronously = runContinuationsAsynchronously;
        }

        public PooledValueTaskSource Create()
            => new(_owner, _runContinuationsAsynchronously);

        public bool TryReset(PooledValueTaskSource source) => true;
    }
}

/// <summary>Provides pools of reusable manually completed value task sources.</summary>
/// <typeparam name="T">The operation result type.</typeparam>
[ExcludeFromCodeCoverage]
[DebuggerNonUserCode]
#if RESERVOIR_PUBLIC
public
#else
internal
#endif
sealed class ValueTaskSourcePool<T> : IDisposable
{
    private readonly ObjectPool<PooledValueTaskSource<T>, Policy> _pool;

    /// <summary>Gets the shared pool.</summary>
    public static ValueTaskSourcePool<T> Shared { get; } = new();

    /// <summary>Initializes a pool with the default capacity and inline continuations.</summary>
    public ValueTaskSourcePool()
        : this(
            ObjectPool<PooledValueTaskSource<T>, Policy>.DefaultMaximumRetained,
            runContinuationsAsynchronously: false)
    {
    }

    /// <summary>Initializes a pool with the default capacity and continuation behavior.</summary>
    public ValueTaskSourcePool(bool runContinuationsAsynchronously)
        : this(
            ObjectPool<PooledValueTaskSource<T>, Policy>.DefaultMaximumRetained,
            runContinuationsAsynchronously)
    {
    }

    /// <summary>Initializes a pool with a custom capacity and continuation behavior.</summary>
    public ValueTaskSourcePool(
        int maxCapacity,
        bool runContinuationsAsynchronously = false)
    {
        RunContinuationsAsynchronously = runContinuationsAsynchronously;
        _pool = new ObjectPool<PooledValueTaskSource<T>, Policy>(
            new Policy(this, runContinuationsAsynchronously),
            maxCapacity);
    }

    /// <summary>Gets the maximum number of sources retained by this pool.</summary>
    public int MaximumRetained => _pool.MaximumRetained;

    /// <summary>Gets whether continuations are scheduled asynchronously.</summary>
    public bool RunContinuationsAsynchronously { get; }

    /// <summary>Rents a source that returns to this pool when its value task is consumed.</summary>
    public PooledValueTaskSource<T> Rent() => _pool.Rent();

    /// <summary>Removes all retained sources while leaving the pool usable.</summary>
    public void Clear() => _pool.Clear();

    /// <summary>Closes a dedicated pool. Disposing <see cref="Shared"/> only clears it.</summary>
    public void Dispose()
    {
        if (ReferenceEquals(this, Shared))
        {
            _pool.Clear();
            return;
        }

        _pool.Dispose();
    }

    internal void Return(PooledValueTaskSource<T> source) => _pool.Return(source);

    internal readonly struct Policy : IPooledObjectPolicy<PooledValueTaskSource<T>>
    {
        private readonly ValueTaskSourcePool<T> _owner;
        private readonly bool _runContinuationsAsynchronously;

        internal Policy(ValueTaskSourcePool<T> owner, bool runContinuationsAsynchronously)
        {
            _owner = owner;
            _runContinuationsAsynchronously = runContinuationsAsynchronously;
        }

        public PooledValueTaskSource<T> Create()
            => new(_owner, _runContinuationsAsynchronously);

        public bool TryReset(PooledValueTaskSource<T> source) => true;
    }
}
